-- Migração para atualizar conteúdo ENEM das matérias Física, Química, Biologia e História
-- Primeiro, limpar o conteúdo existente dessas matérias
DELETE FROM public.subject_contents 
WHERE subject IN ('Física', 'Química', 'Biologia', 'História');

-- Inserir novo conteúdo estruturado de Física
INSERT INTO public.subject_contents (subject, grande_tema, title, description, detailed_explanation, explanation, examples, content_type, difficulty_level, estimated_time) VALUES

-- Mecânica
('Física', 'Mecânica', 'Cinemática (velocidade, aceleração, MUV)', 'É o estudo do movimento. É a base da Física e um dos temas mais presentes no exame.', 'A Cinemática descreve o movimento sem se preocupar com suas causas. Conceitos-chave: posição, deslocamento, velocidade (média e instantânea) e aceleração. O Movimento Uniforme (MU) tem velocidade constante. O Movimento Uniformemente Variado (MUV) tem aceleração constante.', 'O mais importante é a interpretação de gráficos (posição x tempo, velocidade x tempo). Saber que a inclinação do gráfico v x t é a aceleração e a área sob ele é o deslocamento resolve muitas questões. As "funções horárias" (sorvete, sorvetão) são ferramentas para modelar situações-problema, como o encontro de dois veículos.', 'Uma questão pode apresentar o gráfico da velocidade de um carro durante uma viagem e pedir para calcular a distância total percorrida (calculando a área do gráfico) ou em qual trecho a aceleração foi maior (analisando a inclinação).', 'theory', 'medium', 20),

('Física', 'Mecânica', 'Leis de Newton e Dinâmica', 'É o estudo do movimento. É a base da Física e um dos temas mais presentes no exame.', 'A Dinâmica estuda as causas do movimento. As Três Leis de Newton são o pilar: 1ª (Inércia), 2ª (Princípio Fundamental: F=ma) e 3ª (Ação e Reação).', 'O conceito de Inércia é muito cobrado (ex: por que usamos cinto de segurança?). A Segunda Lei é a ferramenta de cálculo principal, aplicada em problemas com força peso, força normal, força de atrito e tração. A Terceira Lei é conceitual: o par ação-reação atua em corpos diferentes, tem mesma intensidade, mesma direção e sentidos opostos.', 'Calcular a força necessária para empurrar um bloco sobre uma superfície com atrito, ou entender por que, ao caminhar, empurramos o chão para trás (ação) e o chão nos empurra para frente (reação).', 'theory', 'medium', 25),

('Física', 'Mecânica', 'Trabalho e Energia (cinética, potencial, conservação)', 'É o estudo do movimento. É a base da Física e um dos temas mais presentes no exame.', 'Trabalho é a transferência de energia através de uma força. Energia é a capacidade de realizar trabalho. Principais tipos: Cinética (associada ao movimento), Potencial Gravitacional (associada à altura) e Potencial Elástica (associada a molas).', 'O conceito de Conservação da Energia Mecânica é fundamental. Em sistemas sem atrito, a energia mecânica total (soma da cinética e potencial) se mantém constante. Questões de montanha-russa, pêndulos e objetos em queda livre são clássicas. Você precisa saber igualar a energia em dois pontos diferentes do percurso.', 'Um carrinho de montanha-russa parte do repouso no ponto mais alto. Qual será sua velocidade na base da montanha? Você iguala a Energia Potencial Gravitacional no topo com a Energia Cinética na base.', 'theory', 'medium', 22),

('Física', 'Mecânica', 'Gravitação Universal', 'É o estudo do movimento. É a base da Física e um dos temas mais presentes no exame.', 'O estudo da força de atração entre corpos com massa, descrita pela Lei de Newton, e do movimento de planetas e satélites, descrito pelas Leis de Kepler.', 'As Leis de Kepler são cobradas de forma conceitual (planetas descrevem órbitas elípticas; a linha que liga o planeta ao Sol varre áreas iguais em tempos iguais). A Lei da Gravitação Universal pode aparecer em questões que comparam a força da gravidade em diferentes planetas ou a diferentes distâncias da Terra.', 'Uma questão pode afirmar que um satélite se move mais rápido quando está mais perto da Terra (periélio) e perguntar a qual Lei de Kepler esse fenômeno se refere (2ª Lei).', 'theory', 'medium', 18),

-- Eletricidade e Magnetismo
('Física', 'Eletricidade e Magnetismo', 'Eletrodinâmica (circuitos, Leis de Ohm, potência)', 'Este tema é extremamente relevante para o mundo moderno e muito cobrado no ENEM, principalmente a parte de circuitos elétricos.', 'O estudo das cargas elétricas em movimento (corrente elétrica). Conceitos-chave: corrente (i), tensão ou ddp (U) e resistência (R). A 1ª Lei de Ohm (U = R.i) relaciona essas três grandezas. Potência Elétrica (P = U.i) mede a energia consumida por tempo.', 'É o assunto de física que mais cai. Você precisa saber analisar circuitos simples, com resistores em série (a corrente é a mesma) e em paralelo (a tensão é a mesma). Questões sobre o funcionamento de aparelhos domésticos, consumo de energia (em kWh), chuveiros elétricos (relação entre potência, resistência e temperatura) e curto-circuito são muito comuns.', '"Por que ao ligar o chuveiro na posição ''inverno'' (mais quente) a conta de luz aumenta?" Porque na posição inverno a resistência é menor, o que, pela Lei de Ohm, aumenta a corrente e, consequentemente, a potência (P=R.i²).', 'theory', 'hard', 25),

('Física', 'Eletricidade e Magnetismo', 'Eletrostática (cargas, campo elétrico)', 'Este tema é extremamente relevante para o mundo moderno e muito cobrado no ENEM, principalmente a parte de circuitos elétricos.', 'O estudo das cargas elétricas em repouso. Conceitos: carga elétrica, processos de eletrização (atrito, contato, indução), força elétrica (Lei de Coulomb) e campo elétrico.', 'A prova foca nos conceitos. Você precisa entender como os corpos se eletrizam e o que acontece com as cargas. O conceito de campo elétrico como uma região de influência de uma carga é importante, mas os cálculos da Lei de Coulomb são menos frequentes que os de circuitos.', 'Uma questão pode descrever um experimento onde um bastão de vidro atrai pedaços de papel e perguntar qual o processo de eletrização envolvido (indução).', 'theory', 'medium', 20),

('Física', 'Eletricidade e Magnetismo', 'Magnetismo (campo magnético, força magnética)', 'Este tema é extremamente relevante para o mundo moderno e muito cobrado no ENEM, principalmente a parte de circuitos elétricos.', 'O estudo dos fenômenos relacionados a ímãs e campos magnéticos. Conceitos: polos magnéticos, campo magnético (gerado por ímãs ou por correntes elétricas - Experiência de Oersted), força magnética e indução eletromagnética.', 'O foco é conceitual. Entender que não existem monopolos magnéticos, como funcionam bússolas e o campo magnético da Terra. A relação entre eletricidade e magnetismo é crucial: corrente elétrica gera campo magnético (base dos eletroímãs) e a variação do campo magnético gera corrente elétrica (base dos geradores e usinas de energia).', 'Entender o princípio de funcionamento de um motor elétrico (força magnética atuando em um fio com corrente) ou de uma usina hidrelétrica (a água move uma turbina, que gira um ímã perto de uma bobina, induzindo uma corrente elétrica).', 'theory', 'medium', 22),

-- Termologia e Ondulatória
('Física', 'Termologia e Ondulatória', 'Calorimetria (calor sensível e latente, trocas de calor)', 'Fenômenos relacionados ao calor, temperatura, som e luz. São temas muito visuais e presentes no nosso dia a dia.', 'O estudo das trocas de calor. Temperatura é a medida da agitação das partículas. Calor é a energia térmica em trânsito. Calor Sensível é o que causa variação de temperatura (Q=mcΔT). Calor Latente é o que causa mudança de estado físico (Q=mL).', 'O ENEM cobra o entendimento desses conceitos em situações práticas, como o porquê de sentirmos frio ao sair molhados da piscina (a água evapora, "roubando" calor do nosso corpo) ou por que a panela de pressão cozinha mais rápido (a pressão aumenta o ponto de ebulição da água). Cálculos de trocas de calor em sistemas isolados (a soma dos calores trocados é zero) também são comuns.', 'Calcular a quantidade de calor necessária para transformar um bloco de gelo a -10°C em água a 20°C, envolvendo calor sensível do gelo, calor latente de fusão e calor sensível da água.', 'theory', 'medium', 20),

('Física', 'Termologia e Ondulatória', 'Termodinâmica', 'Fenômenos relacionados ao calor, temperatura, som e luz. São temas muito visuais e presentes no nosso dia a dia.', 'O estudo das relações entre calor, trabalho e energia, principalmente em gases. É a base do funcionamento de motores e refrigeradores.', 'A 1ª Lei da Termodinâmica (conservação de energia: ΔU = Q - W) é a mais importante. As questões geralmente envolvem a análise de transformações gasosas (isobárica, isocórica, isotérmica) e o funcionamento de máquinas térmicas, pedindo para identificar o rendimento ou analisar o ciclo em um gráfico PxV.', 'Uma questão pode descrever o ciclo de um motor de carro e perguntar em qual etapa o gás realiza trabalho ou recebe calor, analisando um gráfico.', 'theory', 'hard', 25),

('Física', 'Termologia e Ondulatória', 'Ondulatória (fenômenos como refração, reflexão, difração)', 'Fenômenos relacionados ao calor, temperatura, som e luz. São temas muito visuais e presentes no nosso dia a dia.', 'O estudo das ondas (mecânicas, como o som, ou eletromagnéticas, como a luz). Conceitos: frequência, período, comprimento de onda, amplitude e velocidade (v=λf).', 'O mais importante é entender os fenômenos ondulatórios: Reflexão (a onda bate e volta), Refração (a onda muda de meio e de velocidade), Difração (a onda contorna obstáculos), Interferência (ondas se somam ou se anulam) e Polarização. O ENEM cobra a identificação desses fenômenos em situações cotidianas.', 'Entender que o eco é um exemplo de reflexão do som, que um fone de ouvido com cancelamento de ruído usa interferência destrutiva, e que a luz passando por uma fresta e se espalhando é um exemplo de difração.', 'theory', 'medium', 18),

('Física', 'Termologia e Ondulatória', 'Óptica (lentes, espelhos, problemas de visão)', 'Fenômenos relacionados ao calor, temperatura, som e luz. São temas muito visuais e presentes no nosso dia a dia.', 'O ramo da física que estuda a luz e os fenômenos da visão.', 'A formação de imagens em espelhos planos e esféricos e em lentes delgadas (convergentes e divergentes) é o ponto central. O ENEM adora questões sobre o olho humano e seus defeitos de visão: Miopia (dificuldade de ver de longe, corrigida com lente divergente) e Hipermetropia (dificuldade de ver de perto, corrigida com lente convergente).', 'Uma questão pode mostrar o esquema de um olho míope, onde a imagem se forma antes da retina, e perguntar qual tipo de lente deve ser usada para corrigir o problema.', 'theory', 'medium', 20);

-- Inserir conteúdo de Química
INSERT INTO public.subject_contents (subject, grande_tema, title, description, detailed_explanation, explanation, examples, content_type, difficulty_level, estimated_time) VALUES

-- Química Geral e Físico-Química
('Química', 'Química Geral e Físico-Química', 'Estrutura Atômica e Tabela Periódica', 'É a base que explica como a matéria é formada e como ela se transforma.', 'O estudo do átomo (prótons, nêutrons, elétrons) e a organização dos elementos na Tabela Periódica.', 'Entender a distribuição eletrônica é fundamental para prever o comportamento de um elemento. Da Tabela Periódica, o mais importante é compreender as propriedades periódicas (raio atômico, energia de ionização, eletronegatividade) e como elas variam, pois isso explica por que e como os átomos se ligam.', 'Comparar o raio atômico de dois elementos com base em sua posição na tabela para prever qual deles formará um cátion mais facilmente.', 'theory', 'medium', 20),

('Química', 'Química Geral e Físico-Química', 'Ligações Químicas e Forças Intermoleculares', 'É a base que explica como a matéria é formada e como ela se transforma.', 'Ligações Químicas unem os átomos para formar moléculas (Iônica, Covalente, Metálica). Forças Intermoleculares unem as moléculas umas às outras (Dipolo-dipolo, Ligação de Hidrogênio, Forças de London).', 'Este tópico é crucial para entender as propriedades das substâncias. A polaridade de uma ligação e de uma molécula determina o tipo de força intermolecular, que por sua vez explica propriedades como ponto de ebulição, solubilidade ("semelhante dissolve semelhante") e estado físico.', 'Explicar por que o álcool (etanol) se dissolve na água (ambos são polares e fazem ligações de hidrogênio), mas o óleo não (é apolar).', 'theory', 'medium', 25),

('Química', 'Química Geral e Físico-Química', 'Soluções e Cálculo de Concentração', 'É a base que explica como a matéria é formada e como ela se transforma.', 'O estudo de misturas homogêneas (soluções), formadas por um soluto (o que é dissolvido) e um solvente (o que dissolve).', 'O cálculo das diferentes formas de concentração é muito cobrado: concentração comum (g/L), molaridade (mol/L), título (% em massa ou volume) e ppm (partes por milhão). As questões geralmente envolvem a preparação ou a diluição de soluções em contextos como medicina, indústria de alimentos ou controle de poluição.', 'Calcular a massa de sal necessária para preparar 500 mL de soro fisiológico com concentração de 9 g/L.', 'theory', 'hard', 22),

('Química', 'Química Geral e Físico-Química', 'Termoquímica (entalpia, reações exo/endotérmicas)', 'É a base que explica como a matéria é formada e como ela se transforma.', 'O estudo do calor envolvido nas reações químicas. Entalpia (H) é o conteúdo de energia de uma substância. Reações exotérmicas liberam calor (ΔH < 0), enquanto reações endotérmicas absorvem calor (ΔH > 0).', 'O ENEM cobra a identificação de processos exo/endotérmicos no cotidiano (combustão é exotérmica, fotossíntese é endotérmica). A Lei de Hess (o ΔH total não depende do caminho da reação) pode aparecer em questões que pedem para calcular a variação de entalpia de uma reação a partir de outras.', 'Analisar um gráfico de entalpia de uma reação para determinar se ela é exotérmica ou endotérmica e calcular o valor do ΔH.', 'theory', 'medium', 20),

('Química', 'Química Geral e Físico-Química', 'Cinética e Equilíbrio Químico', 'É a base que explica como a matéria é formada e como ela se transforma.', 'Cinética estuda a velocidade das reações e os fatores que a influenciam (temperatura, concentração, superfície de contato, catalisadores). Equilíbrio é o estado em que a velocidade da reação direta se iguala à da inversa.', 'Para cinética, o foco é qualitativo: entender por que alimentos cozinham mais rápido na panela de pressão (maior temperatura e pressão) ou por que um comprimido efervescente se dissolve mais rápido em pó (maior superfície de contato). Para equilíbrio, o Princípio de Le Chatelier é a estrela: "Quando um sistema em equilíbrio é perturbado, ele se desloca no sentido de anular essa perturbação".', 'Em uma reação em equilíbrio, prever para que lado a reação se desloca se aumentarmos a pressão, a temperatura ou a concentração de um dos reagentes.', 'theory', 'hard', 25),

-- Química Orgânica
('Química', 'Química Orgânica', 'Funções Orgânicas (álcool, cetona, ácidos, etc.)', 'O estudo dos compostos de carbono. É uma parte enorme da química, mas o ENEM foca nos conceitos mais aplicados.', 'É a classificação dos compostos orgânicos com base em seus grupos funcionais.', 'O mais importante é reconhecer as principais funções: hidrocarbonetos, álcool, fenol, éter, aldeído, cetona, ácido carboxílico, éster, amina e amida. Saber a nomenclatura básica ajuda, mas o reconhecimento da estrutura e a associação com suas propriedades (ex: ácidos carboxílicos são ácidos, aminas são básicas) é o principal.', 'Dada a fórmula estrutural do paracetamol, identificar as funções fenol e amida presentes na molécula.', 'theory', 'medium', 22),

('Química', 'Química Orgânica', 'Reações Orgânicas Principais', 'O estudo dos compostos de carbono. É uma parte enorme da química, mas o ENEM foca nos conceitos mais aplicados.', 'Os processos de transformação que os compostos orgânicos sofrem.', 'O ENEM não espera que você decore mecanismos complexos. O foco é em reações de grande importância industrial ou biológica: Combustão (de combustíveis fósseis), Esterificação (formação de essências e gorduras), Saponificação (produção de sabão), Oxidação (de álcoois, como no teste do bafômetro) e Polimerização.', 'Entender que a reação entre um ácido carboxílico (vinagre) e um álcool (álcool de cozinha) forma um éster, que tem cheiro de fruta.', 'theory', 'medium', 20),

('Química', 'Química Orgânica', 'Isomeria (plana e espacial)', 'O estudo dos compostos de carbono. É uma parte enorme da química, mas o ENEM foca nos conceitos mais aplicados.', 'O fenômeno em que duas ou mais substâncias diferentes possuem a mesma fórmula molecular. Isomeria Plana (de função, de cadeia, de posição). Isomeria Espacial ou Estereoisomeria (Geométrica cis-trans e Óptica).', 'A isomeria explica por que compostos com a mesma "receita" (fórmula molecular) podem ter cheiros, sabores e efeitos biológicos completamente diferentes. A isomeria geométrica (cis-trans) é importante em gorduras e visão. A isomeria óptica (quiralidade) é fundamental em fármacos e bioquímica.', 'Entender a diferença entre a gordura cis (saudável) e a gordura trans (prejudicial), que são isômeros geométricos.', 'theory', 'hard', 25),

('Química', 'Química Orgânica', 'Polímeros', 'O estudo dos compostos de carbono. É uma parte enorme da química, mas o ENEM foca nos conceitos mais aplicados.', 'Macromoléculas formadas pela repetição de pequenas unidades (monômeros).', 'O ENEM aborda os polímeros de grande importância comercial e cotidiana: plásticos (PET, PVC, PE), borrachas, nylon, e também polímeros naturais como carboidratos (amido, celulose) e proteínas. É importante saber reconhecer a unidade de repetição (o monômero) e o tipo de reação que forma o polímero (adição ou condensação).', 'Uma questão pode mostrar a estrutura do polímero PET e pedir para identificar o monômero ou a função orgânica (éster) que se repete.', 'theory', 'medium', 18),

-- Química Ambiental e Inorgânica
('Química', 'Química Ambiental e Inorgânica', 'Poluição (água, solo, ar)', 'A aplicação da química para entender o mundo ao nosso redor, desde a poluição até os produtos de limpeza.', 'A introdução de substâncias ou energia no ambiente, causando impacto negativo.', 'Este é um tema interdisciplinar (dialoga com Biologia e Geografia). Conceitos importantes: Efeito Estufa (gases como CO₂ e CH₄), Chuva Ácida (óxidos de enxofre e nitrogênio), Destruição da Camada de Ozônio (CFCs) e Eutrofização (excesso de nutrientes na água).', 'Uma questão pode relacionar o aumento da queima de combustíveis fósseis com a intensificação do efeito estufa ou com a formação de chuva ácida.', 'theory', 'medium', 20),

('Química', 'Química Ambiental e Inorgânica', 'Lixo e Reciclagem', 'A aplicação da química para entender o mundo ao nosso redor, desde a poluição até os produtos de limpeza.', 'O estudo do destino dos resíduos sólidos e dos processos para reaproveitá-los.', 'Entender os diferentes tipos de materiais (metais, vidros, plásticos, papel) e os processos básicos de sua reciclagem. A coleta seletiva e a simbologia da reciclagem são temas recorrentes.', 'Uma questão pode apresentar os símbolos de reciclagem de diferentes plásticos e pedir para associá-los a seus usos comuns (ex: PET em garrafas).', 'theory', 'easy', 15),

('Química', 'Química Ambiental e Inorgânica', 'Funções Inorgânicas (ácidos, bases, sais e óxidos)', 'A aplicação da química para entender o mundo ao nosso redor, desde a poluição até os produtos de limpeza.', 'A classificação dos compostos que não são orgânicos.', 'O foco é no comportamento e nas aplicações. Ácidos e Bases (conceito de Arrhenius, escala de pH, reações de neutralização). Sais (formados na neutralização). Óxidos (e sua classificação em ácidos, básicos, neutros ou anfóteros). As questões contextualizam esses compostos em produtos de limpeza, alimentos, chuva ácida, etc.', 'Entender por que se joga cal (um óxido básico) em solos ácidos para corrigir o pH, através de uma reação de neutralização.', 'theory', 'medium', 22),

('Química', 'Química Ambiental e Inorgânica', 'Estequiometria', 'A aplicação da química para entender o mundo ao nosso redor, desde a poluição até os produtos de limpeza.', 'O cálculo das quantidades de reagentes e produtos envolvidos em uma reação química, com base nas leis de conservação de massa.', 'É a "matemática da química". Aparece em muitas questões, de forma direta ou indireta. Você precisa saber balancear uma equação química e usar a proporção em mols (dada pelos coeficientes) para calcular massas, volumes ou número de partículas. Casos de reagente limitante/excesso e pureza/rendimento são comuns.', '"Na queima completa de 160g de metano (CH₄), qual a massa de dióxido de carbono (CO₂) produzida?" Você precisa montar e balancear a equação, converter a massa de metano para mols, usar a proporção da equação para achar os mols de CO₂ e, por fim, converter de volta para massa.', 'theory', 'hard', 30);

-- Inserir conteúdo de Biologia
INSERT INTO public.subject_contents (subject, grande_tema, title, description, detailed_explanation, explanation, examples, content_type, difficulty_level, estimated_time) VALUES

-- Ecologia e Meio Ambiente
('Biologia', 'Ecologia e Meio Ambiente', 'Cadeias e Teias Alimentares', 'Este é, de longe, o tema mais cobrado em Biologia no ENEM.', 'A representação do fluxo de energia e matéria nos ecossistemas. Cadeia alimentar é linear (produtor -> consumidor primário -> ...). Teia alimentar é um conjunto de cadeias interligadas, mostrando a complexidade das relações.', 'Você precisa saber identificar os níveis tróficos (produtores, consumidores, decompositores) e entender que a energia flui de forma unidirecional, perdendo-se calor a cada nível. Questões sobre bioacumulação ou magnificação trófica (acúmulo de compostos tóxicos ao longo da cadeia) são muito comuns.', 'Uma questão pode descrever a contaminação de um rio por mercúrio e perguntar em qual organismo da cadeia alimentar (plâncton, peixe pequeno, peixe grande, ave pescadora) a concentração do metal será maior.', 'theory', 'medium', 20),

('Biologia', 'Ecologia e Meio Ambiente', 'Ciclos Biogeoquímicos (carbono, nitrogênio)', 'Este é, de longe, o tema mais cobrado em Biologia no ENEM.', 'O caminho que os elementos químicos (como carbono, nitrogênio, água) percorrem entre os seres vivos (bio) e o ambiente (geo).', 'O Ciclo do Carbono é fundamental para entender o aquecimento global (a queima de combustíveis fósseis libera CO₂ que estava "preso"). O Ciclo do Nitrogênio é importante pela ação das bactérias no solo (fixação, nitrificação), essencial para a agricultura.', 'Relacionar o desmatamento da Amazônia com alterações no ciclo do carbono (menos fotossíntese para absorver CO₂) e no ciclo da água (menos evapotranspiração, alterando o regime de chuvas).', 'theory', 'medium', 22),

('Biologia', 'Ecologia e Meio Ambiente', 'Relações Ecológicas', 'Este é, de longe, o tema mais cobrado em Biologia no ENEM.', 'As interações entre os seres vivos. Podem ser intraespecíficas (mesma espécie) ou interespecíficas (espécies diferentes), e harmônicas (+/+, +/0) ou desarmônicas (+/-, -/-).', 'O ENEM apresenta um cenário e pede para você identificar a relação. Exemplos clássicos: Mutualismo (+/+, ex: líquen), Predatismo (+/-), Parasitismo (+/-), Competição (-/-), Comensalismo (+/0, ex: rêmora e tubarão).', 'Descrever a relação entre uma orquídea que vive no tronco de uma árvore (epifitismo, um tipo de inquilinismo, +/0) ou entre o cupim e os protozoários em seu intestino que digerem a celulose (mutualismo).', 'theory', 'medium', 18),

('Biologia', 'Ecologia e Meio Ambiente', 'Impactos Ambientais e Desequilíbrios', 'Este é, de longe, o tema mais cobrado em Biologia no ENEM.', 'As consequências das ações humanas nos ecossistemas.', 'Tema interdisciplinar que aparece em toda a prova. Você precisa entender as causas e consequências de problemas como: desmatamento, assoreamento de rios, poluição, introdução de espécies exóticas, aquecimento global, eutrofização, magnificação trófica.', 'Uma questão pode explicar como o esgoto doméstico, rico em matéria orgânica, lançado em um lago causa a proliferação de algas, que ao morrerem são decompostas por bactérias que consomem todo o oxigênio da água, matando os peixes (processo de eutrofização).', 'theory', 'medium', 25),

-- Citologia, Histologia e Bioquímica
('Biologia', 'Citologia, Histologia e Bioquímica', 'Membrana Plasmática e Organelas Celulares', 'O estudo da célula, dos tecidos e das moléculas que compõem a vida.', 'O estudo da estrutura e função das partes da célula.', 'O modelo do mosaico fluido da membrana plasmática e seus transportes (difusão, osmose, transporte ativo) são muito importantes. Sobre as organelas, o foco é na função: Mitocôndria (respiração celular e energia), Ribossomos (síntese de proteínas), Retículo Endoplasmático (produção e transporte), Complexo de Golgi (armazenamento e secreção) e Cloroplastos (fotossíntese, em células vegetais).', 'Uma célula muscular precisa de muita energia, portanto, é rica em mitocôndrias. Uma célula do pâncreas que produz insulina (proteína) é rica em ribossomos e complexo de Golgi.', 'theory', 'medium', 25),

('Biologia', 'Citologia, Histologia e Bioquímica', 'Bioenergética (fotossíntese e respiração celular)', 'O estudo da célula, dos tecidos e das moléculas que compõem a vida.', 'O estudo de como os seres vivos obtêm e transformam energia.', 'O mais importante é entender a equação geral e o balanço energético dos dois processos. Respiração Celular (ocorre na mitocôndria, consome glicose e O₂ para produzir ATP, CO₂ e água). Fotossíntese (ocorre nos cloroplastos, usa CO₂, água e luz para produzir glicose e O₂). Entender que são processos interdependentes é crucial.', 'Uma questão pode pedir para analisar um gráfico que mostra a taxa de fotossíntese de uma planta em diferentes intensidades de luz.', 'theory', 'medium', 22),

('Biologia', 'Citologia, Histologia e Bioquímica', 'Histologia (tecidos animais)', 'O estudo da célula, dos tecidos e das moléculas que compõem a vida.', 'O estudo dos tecidos do corpo.', 'O foco é na relação entre a estrutura do tecido e sua função. Tecido Epitelial (revestimento e glândulas), Tecido Conjuntivo (sustentação e preenchimento - inclui sangue, osso, cartilagem), Tecido Muscular (contração e movimento) e Tecido Nervoso (transmissão de impulsos).', 'Entender por que o tecido muscular cardíaco tem tantas mitocôndrias (alta demanda de energia) e junções que permitem a contração sincronizada.', 'theory', 'medium', 20),

('Biologia', 'Citologia, Histologia e Bioquímica', 'Bioquímica Celular', 'O estudo da célula, dos tecidos e das moléculas que compõem a vida.', 'O estudo das moléculas da vida.', 'Entender a função básica de cada grupo: Carboidratos (energia imediata e estrutura, ex: glicose, amido), Lipídios (reserva de energia, isolante térmico, hormônios), Proteínas (função estrutural, enzimática, defesa - são polímeros de aminoácidos) e Vitaminas (atuam como coenzimas).', 'Uma questão pode relacionar uma dieta pobre em proteína com problemas no sistema imunológico (já que os anticorpos são proteínas).', 'theory', 'medium', 18),

-- Genética e Evolução
('Biologia', 'Genética e Evolução', 'Leis de Mendel', 'O estudo da hereditariedade e das mudanças nos seres vivos ao longo do tempo.', 'As leis básicas da hereditariedade. 1ª Lei (segregação de um par de fatores) e 2ª Lei (segregação independente de dois ou mais pares).', 'O ENEM cobra a aplicação dessas leis na resolução de problemas de heredogramas (árvores genealógicas), onde você precisa descobrir genótipos e a probabilidade de um casal ter um filho com determinada característica.', 'Analisar um heredograma de uma família com casos de albinismo e calcular a probabilidade de um casal ter um filho albino.', 'theory', 'hard', 25),

('Biologia', 'Genética e Evolução', 'Engenharia Genética e Biotecnologia', 'O estudo da hereditariedade e das mudanças nos seres vivos ao longo do tempo.', 'A manipulação do DNA para obter produtos de interesse.', 'Tema moderno e muito relevante. Conceitos importantes: DNA Recombinante, Transgênicos (organismos que recebem um gene de outra espécie), Clonagem e Terapia Gênica. As questões abordam as aplicações (produção de insulina, plantas mais resistentes) e as implicações éticas.', 'Entender como a inserção de um gene humano em uma bactéria faz com que ela passe a produzir insulina, que pode ser usada por diabéticos.', 'theory', 'hard', 22),

('Biologia', 'Genética e Evolução', 'Teorias Evolutivas (Lamarck e Darwin)', 'O estudo da hereditariedade e das mudanças nos seres vivos ao longo do tempo.', 'As explicações sobre como a vida se diversificou.', 'A principal tarefa é diferenciar Lamarck de Darwin. Lamarck: Lei do uso e desuso e herança dos caracteres adquiridos (ideia errada, mas importante historicamente). Darwin: Seleção Natural (o meio ambiente seleciona os indivíduos mais aptos, que sobrevivem e deixam mais descendentes). O Neodarwinismo incorpora os conhecimentos da genética à teoria de Darwin.', 'Uma questão clássica descreve o pescoço da girafa. A explicação de Lamarck seria que a girafa "esticou" o pescoço para alcançar as folhas e passou essa característica para os filhos. A de Darwin seria que já existiam girafas com pescoços de tamanhos variados; as de pescoço mais longo conseguiam mais comida, sobreviviam mais e, portanto, deixavam mais descendentes com essa característica.', 'theory', 'medium', 20),

('Biologia', 'Genética e Evolução', 'Hereditariedade e Grupos Sanguíneos', 'O estudo da hereditariedade e das mudanças nos seres vivos ao longo do tempo.', 'O estudo de casos específicos de herança genética.', 'O sistema ABO é o mais cobrado. É um caso de alelos múltiplos e codominância (os alelos I^A e I^B são dominantes sobre o i, mas não há dominância entre eles). Você precisa saber determinar o tipo sanguíneo dos filhos a partir dos pais e entender as regras de transfusão de sangue.', 'Um homem do tipo sanguíneo A e uma mulher do tipo B têm um filho do tipo O. Quais os genótipos dos pais? (Ambos são heterozigotos: I^A i e I^B i).', 'theory', 'medium', 18),

-- Fisiologia Humana e Saúde
('Biologia', 'Fisiologia Humana e Saúde', 'Sistemas do Corpo Humano', 'O estudo do funcionamento do corpo humano e das doenças que o afetam.', 'O estudo integrado dos sistemas que mantêm o corpo funcionando.', 'O ENEM cobra a integração entre os sistemas. Digestório (ação das enzimas), Respiratório (trocas gasosas nos alvéolos), Circulatório (transporte de gases e nutrientes), Excretor (filtração do sangue nos rins), Endócrino (ação dos hormônios, como insulina e glucagon) e Nervoso (transmissão do impulso nervoso).', 'Uma questão pode relacionar a prática de exercícios físicos com o aumento da frequência respiratória e cardíaca, mostrando a integração entre os sistemas muscular, respiratório e circulatório para suprir a demanda de oxigênio.', 'theory', 'medium', 25),

('Biologia', 'Fisiologia Humana e Saúde', 'Imunologia (vacinas, soros)', 'O estudo do funcionamento do corpo humano e das doenças que o afetam.', 'O estudo do sistema de defesa do corpo.', 'A diferença entre vacina e soro é um clássico. Vacina: imunização ativa e preventiva. Contém o antígeno (vírus atenuado/morto) para que o seu corpo produza anticorpos e memória imunológica. Soro: imunização passiva e de emergência/cura. Contém os anticorpos já prontos para combater um antígeno específico (ex: picada de cobra).', 'Explicar por que uma pessoa que foi picada por uma cobra peçonhenta deve tomar o soro antiofídico e não uma vacina.', 'theory', 'medium', 20),

('Biologia', 'Fisiologia Humana e Saúde', 'Parasitologia e Principais Doenças', 'O estudo do funcionamento do corpo humano e das doenças que o afetam.', 'O estudo das doenças causadas por vírus, bactérias, protozoários e vermes.', 'O ENEM adora questões que envolvem profilaxia (medidas de prevenção). Para cada doença, você deve saber o agente causador, o vetor (se houver) e, principalmente, como evitá-la. Doenças relacionadas a saneamento básico (cólera, esquistossomose), a vetores (dengue, malária, doença de Chagas) e de grande impacto social (AIDS) são as mais comuns.', 'Uma questão sobre esquistossomose vai focar nas medidas para erradicá-la, como saneamento básico (para evitar que os ovos cheguem à água) e o controle do caramujo (hospedeiro intermediário).', 'theory', 'medium', 22);

-- Inserir conteúdo de História
INSERT INTO public.subject_contents (subject, grande_tema, title, description, detailed_explanation, explanation, examples, content_type, difficulty_level, estimated_time) VALUES

-- História do Brasil
('História', 'História do Brasil', 'Brasil Colônia (economia açucareira, mineração)', 'É a parte mais cobrada de História, com foco nos processos sociais, políticos e econômicos que formaram o país.', 'O período em que o Brasil foi colônia de Portugal (1500-1822).', 'Entender a lógica do Pacto Colonial e da economia baseada no plantation (latifúndio, monocultura, mão de obra escrava, produção para exportação). A sociedade era patriarcal e escravista. A mineração no século XVIII deslocou o eixo econômico para o Sudeste e aumentou o controle de Portugal. As revoltas coloniais (ex: Inconfidência Mineira) mostram os primeiros anseios por autonomia.', 'Analisar um texto sobre a vida em um engenho de açúcar, identificando as relações de poder entre senhores, escravos e trabalhadores livres.', 'theory', 'medium', 25),

('História', 'História do Brasil', 'Brasil Império (Primeiro e Segundo Reinado, Crise da Monarquia)', 'É a parte mais cobrada de História, com foco nos processos sociais, políticos e econômicos que formaram o país.', 'O período monárquico do Brasil (1822-1889).', 'O Primeiro Reinado foi marcado pelo autoritarismo de D. Pedro I. O Período Regencial foi uma época de instabilidade e revoltas. O Segundo Reinado (D. Pedro II) foi um longo período de estabilidade política (baseada no "parlamentarismo às avessas") e transformações econômicas (auge do café). O processo de abolição da escravatura e a Guerra do Paraguai são temas centrais que levaram à crise e queda da monarquia.', 'Uma questão pode usar uma charge da época para criticar o Poder Moderador ou discutir o papel dos imigrantes europeus que vieram substituir a mão de obra escrava nas lavouras de café.', 'theory', 'medium', 25),

('História', 'História do Brasil', 'República Velha e Era Vargas', 'É a parte mais cobrada de História, com foco nos processos sociais, políticos e econômicos que formaram o país.', 'A República Velha (1889-1930) foi marcada pelo domínio das oligarquias (política do "café com leite") e pelo coronelismo. A Era Vargas (1930-1945) foi um período de centralização do poder, industrialização, criação das leis trabalhistas (CLT) e forte propaganda política, passando por fases como o Estado Novo (ditadura).', 'Entender as estruturas de poder da República Velha (voto de cabresto, clientelismo). Sobre Vargas, é crucial compreender seu caráter populista, a modernização econômica e a manipulação das massas através do rádio e da propaganda oficial (DIP).', 'Analisar um cartaz de propaganda do Estado Novo e identificar os elementos que buscam exaltar a figura de Getúlio Vargas como "pai dos pobres".', 'theory', 'medium', 25),

('História', 'História do Brasil', 'Ditadura Militar e Redemocratização', 'É a parte mais cobrada de História, com foco nos processos sociais, políticos e econômicos que formaram o país.', 'A Ditadura Militar (1964-1985) foi um regime autoritário que suprimiu direitos políticos e perseguiu opositores, enquanto a Redemocratização (pós-1985) marcou o retorno ao regime democrático no Brasil.', 'Compreender os **Atos Institucionais (AI-5)**, o "milagre econômico" e a repressão política. Na redemocratização, focar nas **Diretas Já**, na **Constituição de 1988** e nos desafios da Nova República.', 'Discutir como a música "Pra Não Dizer que Não Falei das Flores" (Caminhando) de Geraldo Vandré se tornou um hino de resistência à Ditadura Militar, refletindo o contexto de censura e repressão da época.', 'theory', 'hard', 30),

-- História Geral
('História', 'História Geral', 'Antiguidade e Idade Média', 'Aborda os grandes processos históricos globais, com um olhar para as conexões e impactos no presente.', 'A Antiguidade abrange civilizações como Egito, Grécia e Roma. A Idade Média se estende da queda do Império Romano (476 d.C.) até a queda de Constantinopla (1453), caracterizada pelo feudalismo na Europa e o avanço do Islamismo.', 'Foco na **herança cultural greco-romana** (democracia, direito) e nas **estruturas sociais do feudalismo** (clero, nobreza, servos). O papel da Igreja e as Cruzadas também são importantes.', 'Comparar as noções de cidadania na Grécia Antiga com as da Roma Antiga, ou analisar as relações de suserania e vassalagem no contexto feudal.', 'theory', 'medium', 22),

('História', 'História Geral', 'Idade Moderna (Renascimento, Reformas, Absolutismo)', 'Aborda os grandes processos históricos globais, com um olhar para as conexões e impactos no presente.', 'Período de transição para a contemporaneidade (séculos XV-XVIII), marcado pelo **Renascimento** (humanismo e novas artes), **Reforma Protestante** (quebra da unidade religiosa), **Grandes Navegações** (expansão marítima e colonialismo) e o **Absolutismo** (monarquias centralizadas).', 'Entender o **antropocentrismo** do Renascimento, as **críticas à Igreja** que levaram às Reformas (Lutero, Calvino) e a **formação dos Estados Nacionais** e o **mercantilismo** como política econômica colonialista.', 'Analisar uma obra de arte renascentista, como a "Mona Lisa", e discutir seus elementos humanistas e o uso da perspectiva. Ou entender o papel do Rei Sol, Luís XIV, como símbolo do absolutismo.', 'theory', 'medium', 25),

('História', 'História Geral', 'Iluminismo e Revoluções Liberais', 'Aborda os grandes processos históricos globais, com um olhar para as conexões e impactos no presente.', 'O **Iluminismo** (século XVIII) foi um movimento intelectual que valorizava a razão e a crítica ao Antigo Regime. Suas ideias inspiraram a **Revolução Francesa** (1789) e a **Revolução Industrial** (início na Inglaterra, século XVIII), transformando política, sociedade e economia.', 'As **ideias iluministas** (liberdade, igualdade, divisão de poderes) e seu impacto na **crise do absolutismo**. As consequências da **Revolução Francesa** (declaração de direitos, fim dos privilégios) e as transformações sociais (surgimento da classe operária, urbanização) e tecnológicas da **Revolução Industrial**.', 'Relacionar a teoria da separação dos poderes de Montesquieu com a estrutura de governos democráticos atuais, ou discutir o impacto da máquina a vapor na produção têxtil e na vida dos trabalhadores.', 'theory', 'medium', 25),

('História', 'História Geral', 'Século XX (Guerras Mundiais, Guerra Fria, Globalização)', 'Aborda os grandes processos históricos globais, com um olhar para as conexões e impactos no presente.', 'Um século de grandes conflitos e transformações. Inclui a **Primeira (1914-1918) e Segunda (1939-1945) Guerras Mundiais**, a **Guerra Fria** (conflito ideológico EUA x URSS, 1947-1991) e o processo de **Globalização** (intensificação das interconexões mundiais).', 'As **causas e consequências das Guerras Mundiais** (Tratado de Versalhes, ascensão de regimes totalitários, Holocausto, criação da ONU). A **bipolaridade da Guerra Fria** (Muro de Berlim, Corrida Armamentista e Espacial) e a emergência da **Globalização** (avanços tecnológicos, neoliberalismo, blocos econômicos).', 'Explicar como a Crise de 1929 e a ascensão do Nazismo na Alemanha foram fatores que contribuíram para a eclosão da Segunda Guerra Mundial, ou analisar um mapa das divisões ideológicas durante a Guerra Fria.', 'theory', 'hard', 30);