-- Continuação - Inserir conteúdo de Biologia
INSERT INTO public.subject_contents (subject, grande_tema, title, description, detailed_explanation, explanation, examples, content_type, difficulty_level, estimated_time) VALUES

-- Ecologia e Meio Ambiente
('Biologia', 'Ecologia e Meio Ambiente', 'Cadeias e Teias Alimentares', 'Este é, de longe, o tema mais cobrado em Biologia no ENEM.', 'A representação do fluxo de energia e matéria nos ecossistemas. Cadeia alimentar é linear (produtor -> consumidor primário -> ...). Teia alimentar é um conjunto de cadeias interligadas, mostrando a complexidade das relações.', 'Você precisa saber identificar os níveis tróficos (produtores, consumidores, decompositores) e entender que a energia flui de forma unidirecional, perdendo-se calor a cada nível. Questões sobre bioacumulação ou magnificação trófica (acúmulo de compostos tóxicos ao longo da cadeia) são muito comuns.', 'Uma questão pode descrever a contaminação de um rio por mercúrio e perguntar em qual organismo da cadeia alimentar (plâncton, peixe pequeno, peixe grande, ave pescadora) a concentração do metal será maior.', 'theory', 'medium', 20),

('Biologia', 'Ecologia e Meio Ambiente', 'Ciclos Biogeoquímicos (carbono, nitrogênio)', 'Este é, de longe, o tema mais cobrado em Biologia no ENEM.', 'O caminho que os elementos químicos (como carbono, nitrogênio, água) percorrem entre os seres vivos (bio) e o ambiente (geo).', 'O Ciclo do Carbono é fundamental para entender o aquecimento global (a queima de combustíveis fósseis libera CO₂ que estava "preso"). O Ciclo do Nitrogênio é importante pela ação das bactérias no solo (fixação, nitrificação), essencial para a agricultura.', 'Relacionar o desmatamento da Amazônia com alterações no ciclo do carbono (menos fotossíntese para absorver CO₂) e no ciclo da água (menos evapotranspiração, alterando o regime de chuvas).', 'theory', 'medium', 22),

('Biologia', 'Ecologia e Meio Ambiente', 'Relações Ecológicas', 'Este é, de longe, o tema mais cobrado em Biologia no ENEM.', 'As interações entre os seres vivos. Podem ser intraespecíficas (mesma espécie) ou interespecíficas (espécies diferentes), e harmônicas (+/+, +/0) ou desarmônicas (+/-, -/-).', 'O ENEM apresenta um cenário e pede para você identificar a relação. Exemplos clássicos: Mutualismo (+/+, ex: líquen), Predatismo (+/-), Parasitismo (+/-), Competição (-/-), Comensalismo (+/0, ex: rêmora e tubarão).', 'Descrever a relação entre uma orquídea que vive no tronco de uma árvore (epifitismo, um tipo de inquilinismo, +/0) ou entre o cupim e os protozoários em seu intestino que digerem a celulose (mutualismo).', 'theory', 'medium', 18),

('Biologia', 'Ecologia e Meio Ambiente', 'Impactos Ambientais e Desequilíbrios', 'Este é, de longe, o tema mais cobrado em Biologia no ENEM.', 'As consequências das ações humanas nos ecossistemas.', 'Tema interdisciplinar que aparece em toda a prova. Você precisa entender as causas e consequências de problemas como: desmatamento, assoreamento de rios, poluição, introdução de espécies exóticas, aquecimento global, eutrofização, magnificação trófica.', 'Uma questão pode explicar como o esgoto doméstico, rico em matéria orgânica, lançado em um lago causa a proliferação de algas, que ao morrerem são decompostas por bactérias que consomem todo o oxigênio da água, matando os peixes (processo de eutrofização).', 'theory', 'medium', 25),

-- Citologia, Histologia e Bioquímica
('Biologia', 'Citologia, Histologia e Bioquímica', 'Membrana Plasmática e Organelas Celulares', 'O estudo da célula, dos tecidos e das moléculas que compõem a vida.', 'O estudo da estrutura e função das partes da célula.', 'O modelo do mosaico fluido da membrana plasmática e seus transportes (difusão, osmose, transporte ativo) são muito importantes. Sobre as organelas, o foco é na função: Mitocôndria (respiração celular e energia), Ribossomos (síntese de proteínas), Retículo Endoplasmático (produção e transporte), Complexo de Golgi (armazenamento e secreção) e Cloroplastos (fotossíntese, em células vegetais).', 'Uma célula muscular precisa de muita energia, portanto, é rica em mitocôndrias. Uma célula do pâncreas que produz insulina (proteína) é rica em ribossomos e complexo de Golgi.', 'theory', 'medium', 25),

('Biologia', 'Citologia, Histologia e Bioquímica', 'Bioenergética (fotossíntese e respiração celular)', 'O estudo da célula, dos tecidos e das moléculas que compõem a vida.', 'O estudo de como os seres vivos obtêm e transformam energia.', 'O mais importante é entender a equação geral e o balanço energético dos dois processos. Respiração Celular (ocorre na mitocôndria, consome glicose e O₂ para produzir ATP, CO₂ e água). Fotossíntese (ocorre nos cloroplastos, usa CO₂, água e luz para produzir glicose e O₂). Entender que são processos interdependentes é crucial.', 'Uma questão pode pedir para analisar um gráfico que mostra a taxa de fotossíntese de uma planta em diferentes intensidades de luz.', 'theory', 'medium', 22),

('Biologia', 'Citologia, Histologia e Bioquímica', 'Histologia (tecidos animais)', 'O estudo da célula, dos tecidos e das moléculas que compõem a vida.', 'O estudo dos tecidos do corpo.', 'O foco é na relação entre a estrutura do tecido e sua função. Tecido Epitelial (revestimento e glândulas), Tecido Conjuntivo (sustentação e preenchimento - inclui sangue, osso, cartilagem), Tecido Muscular (contração e movimento) e Tecido Nervoso (transmissão de impulsos).', 'Entender por que o tecido muscular cardíaco tem tantas mitocôndrias (alta demanda de energia) e junções que permitem a contração sincronizada.', 'theory', 'medium', 20),

('Biologia', 'Citologia, Histologia e Bioquímica', 'Bioquímica Celular', 'O estudo da célula, dos tecidos e das moléculas que compõem a vida.', 'O estudo das moléculas da vida.', 'Entender a função básica de cada grupo: Carboidratos (energia imediata e estrutura, ex: glicose, amido), Lipídios (reserva de energia, isolante térmico, hormônios), Proteínas (função estrutural, enzimática, defesa - são polímeros de aminoácidos) e Vitaminas (atuam como coenzimas).', 'Uma questão pode relacionar uma dieta pobre em proteína com problemas no sistema imunológico (já que os anticorpos são proteínas).', 'theory', 'medium', 18),

-- Genética e Evolução
('Biologia', 'Genética e Evolução', 'Leis de Mendel', 'O estudo da hereditariedade e das mudanças nos seres vivos ao longo do tempo.', 'As leis básicas da hereditariedade. 1ª Lei (segregação de um par de fatores) e 2ª Lei (segregação independente de dois ou mais pares).', 'O ENEM cobra a aplicação dessas leis na resolução de problemas de heredogramas (árvores genealógicas), onde você precisa descobrir genótipos e a probabilidade de um casal ter um filho com determinada característica.', 'Analisar um heredograma de uma família com casos de albinismo e calcular a probabilidade de um casal ter um filho albino.', 'theory', 'hard', 25),

('Biologia', 'Genética e Evolução', 'Engenharia Genética e Biotecnologia', 'O estudo da hereditariedade e das mudanças nos seres vivos ao longo do tempo.', 'A manipulação do DNA para obter produtos de interesse.', 'Tema moderno e muito relevante. Conceitos importantes: DNA Recombinante, Transgênicos (organismos que recebem um gene de outra espécie), Clonagem e Terapia Gênica. As questões abordam as aplicações (produção de insulina, plantas mais resistentes) e as implicações éticas.', 'Entender como a inserção de um gene humano em uma bactéria faz com que ela passe a produzir insulina, que pode ser usada por diabéticos.', 'theory', 'hard', 22),

('Biologia', 'Genética e Evolução', 'Teorias Evolutivas (Lamarck e Darwin)', 'O estudo da hereditariedade e das mudanças nos seres vivos ao longo do tempo.', 'As explicações sobre como a vida se diversificou.', 'A principal tarefa é diferenciar Lamarck de Darwin. Lamarck: Lei do uso e desuso e herança dos caracteres adquiridos (ideia errada, mas importante historicamente). Darwin: Seleção Natural (o meio ambiente seleciona os indivíduos mais aptos, que sobrevivem e deixam mais descendentes). O Neodarwinismo incorpora os conhecimentos da genética à teoria de Darwin.', 'Uma questão clássica descreve o pescoço da girafa. A explicação de Lamarck seria que a girafa "esticou" o pescoço para alcançar as folhas e passou essa característica para os filhos. A de Darwin seria que já existiam girafas com pescoços de tamanhos variados; as de pescoço mais longo conseguiam mais comida, sobreviviam mais e, portanto, deixavam mais descendentes com essa característica.', 'theory', 'medium', 20),

('Biologia', 'Genética e Evolução', 'Hereditariedade e Grupos Sanguíneos', 'O estudo da hereditariedade e das mudanças nos seres vivos ao longo do tempo.', 'O estudo de casos específicos de herança genética.', 'O sistema ABO é o mais cobrado. É um caso de alelos múltiplos e codominância (os alelos I^A e I^B são dominantes sobre o i, mas não há dominância entre eles). Você precisa saber determinar o tipo sanguíneo dos filhos a partir dos pais e entender as regras de transfusão de sangue.', 'Um homem do tipo sanguíneo A e uma mulher do tipo B têm um filho do tipo O. Quais os genótipos dos pais? (Ambos são heterozigotos: I^A i e I^B i).', 'theory', 'medium', 18),

-- Fisiologia Humana e Saúde
('Biologia', 'Fisiologia Humana e Saúde', 'Sistemas do Corpo Humano', 'O estudo do funcionamento do corpo humano e das doenças que o afetam.', 'O estudo integrado dos sistemas que mantêm o corpo funcionando.', 'O ENEM cobra a integração entre os sistemas. Digestório (ação das enzimas), Respiratório (trocas gasosas nos alvéolos), Circulatório (transporte de gases e nutrientes), Excretor (filtração do sangue nos rins), Endócrino (ação dos hormônios, como insulina e glucagon) e Nervoso (transmissão do impulso nervoso).', 'Uma questão pode relacionar a prática de exercícios físicos com o aumento da frequência respiratória e cardíaca, mostrando a integração entre os sistemas muscular, respiratório e circulatório para suprir a demanda de oxigênio.', 'theory', 'medium', 25),

('Biologia', 'Fisiologia Humana e Saúde', 'Imunologia (vacinas, soros)', 'O estudo do funcionamento do corpo humano e das doenças que o afetam.', 'O estudo do sistema de defesa do corpo.', 'A diferença entre vacina e soro é um clássico. Vacina: imunização ativa e preventiva. Contém o antígeno (vírus atenuado/morto) para que o seu corpo produza anticorpos e memória imunológica. Soro: imunização passiva e de emergência/cura. Contém os anticorpos já prontos para combater um antígeno específico (ex: picada de cobra).', 'Explicar por que uma pessoa que foi picada por uma cobra peçonhenta deve tomar o soro antiofídico e não uma vacina.', 'theory', 'medium', 20),

('Biologia', 'Fisiologia Humana e Saúde', 'Parasitologia e Principais Doenças', 'O estudo do funcionamento do corpo humano e das doenças que o afetam.', 'O estudo das doenças causadas por vírus, bactérias, protozoários e vermes.', 'O ENEM adora questões que envolvem profilaxia (medidas de prevenção). Para cada doença, você deve saber o agente causador, o vetor (se houver) e, principalmente, como evitá-la. Doenças relacionadas a saneamento básico (cólera, esquistossomose), a vetores (dengue, malária, doença de Chagas) e de grande impacto social (AIDS) são as mais comuns.', 'Uma questão sobre esquistossomose vai focar nas medidas para erradicá-la, como saneamento básico (para evitar que os ovos cheguem à água) e o controle do caramujo (hospedeiro intermediário).', 'theory', 'medium', 22);