-- Migração para atualizar conteúdo ENEM - Abordagem Segura
-- Primeiro, remover referências que impedem a limpeza
DELETE FROM public.content_progress 
WHERE content_id IN (
  SELECT id FROM public.subject_contents 
  WHERE subject IN ('Física', 'Química', 'Biologia', 'História')
);

-- Agora limpar o conteúdo existente dessas matérias
DELETE FROM public.subject_contents 
WHERE subject IN ('Física', 'Química', 'Biologia', 'História');

-- Inserir novo conteúdo estruturado de Física
INSERT INTO public.subject_contents (subject, grande_tema, title, description, detailed_explanation, explanation, examples, content_type, difficulty_level, estimated_time) VALUES

-- Mecânica
('Física', 'Mecânica', 'Cinemática (velocidade, aceleração, MUV)', 'É o estudo do movimento. É a base da Física e um dos temas mais presentes no exame.', 'A Cinemática descreve o movimento sem se preocupar com suas causas. Conceitos-chave: posição, deslocamento, velocidade (média e instantânea) e aceleração. O Movimento Uniforme (MU) tem velocidade constante. O Movimento Uniformemente Variado (MUV) tem aceleração constante.', 'O mais importante é a interpretação de gráficos (posição x tempo, velocidade x tempo). Saber que a inclinação do gráfico v x t é a aceleração e a área sob ele é o deslocamento resolve muitas questões. As "funções horárias" (sorvete, sorvetão) são ferramentas para modelar situações-problema, como o encontro de dois veículos.', 'Uma questão pode apresentar o gráfico da velocidade de um carro durante uma viagem e pedir para calcular a distância total percorrida (calculando a área do gráfico) ou em qual trecho a aceleração foi maior (analisando a inclinação).', 'theory', 'medium', 20),

('Física', 'Mecânica', 'Leis de Newton e Dinâmica', 'É o estudo do movimento. É a base da Física e um dos temas mais presentes no exame.', 'A Dinâmica estuda as causas do movimento. As Três Leis de Newton são o pilar: 1ª (Inércia), 2ª (Princípio Fundamental: F=ma) e 3ª (Ação e Reação).', 'O conceito de Inércia é muito cobrado (ex: por que usamos cinto de segurança?). A Segunda Lei é a ferramenta de cálculo principal, aplicada em problemas com força peso, força normal, força de atrito e tração. A Terceira Lei é conceitual: o par ação-reação atua em corpos diferentes, tem mesma intensidade, mesma direção e sentidos opostos.', 'Calcular a força necessária para empurrar um bloco sobre uma superfície com atrito, ou entender por que, ao caminhar, empurramos o chão para trás (ação) e o chão nos empurra para frente (reação).', 'theory', 'medium', 25),

('Física', 'Mecânica', 'Trabalho e Energia (cinética, potencial, conservação)', 'É o estudo do movimento. É a base da Física e um dos temas mais presentes no exame.', 'Trabalho é a transferência de energia através de uma força. Energia é a capacidade de realizar trabalho. Principais tipos: Cinética (associada ao movimento), Potencial Gravitacional (associada à altura) e Potencial Elástica (associada a molas).', 'O conceito de Conservação da Energia Mecânica é fundamental. Em sistemas sem atrito, a energia mecânica total (soma da cinética e potencial) se mantém constante. Questões de montanha-russa, pêndulos e objetos em queda livre são clássicas. Você precisa saber igualar a energia em dois pontos diferentes do percurso.', 'Um carrinho de montanha-russa parte do repouso no ponto mais alto. Qual será sua velocidade na base da montanha? Você iguala a Energia Potencial Gravitacional no topo com a Energia Cinética na base.', 'theory', 'medium', 22),

('Física', 'Mecânica', 'Gravitação Universal', 'É o estudo do movimento. É a base da Física e um dos temas mais presentes no exame.', 'O estudo da força de atração entre corpos com massa, descrita pela Lei de Newton, e do movimento de planetas e satélites, descrito pelas Leis de Kepler.', 'As Leis de Kepler são cobradas de forma conceitual (planetas descrevem órbitas elípticas; a linha que liga o planeta ao Sol varre áreas iguais em tempos iguais). A Lei da Gravitação Universal pode aparecer em questões que comparam a força da gravidade em diferentes planetas ou a diferentes distâncias da Terra.', 'Uma questão pode afirmar que um satélite se move mais rápido quando está mais perto da Terra (periélio) e perguntar a qual Lei de Kepler esse fenômeno se refere (2ª Lei).', 'theory', 'medium', 18),

-- Eletricidade e Magnetismo  
('Física', 'Eletricidade e Magnetismo', 'Eletrodinâmica (circuitos, Leis de Ohm, potência)', 'Este tema é extremamente relevante para o mundo moderno e muito cobrado no ENEM, principalmente a parte de circuitos elétricos.', 'O estudo das cargas elétricas em movimento (corrente elétrica). Conceitos-chave: corrente (i), tensão ou ddp (U) e resistência (R). A 1ª Lei de Ohm (U = R.i) relaciona essas três grandezas. Potência Elétrica (P = U.i) mede a energia consumida por tempo.', 'É o assunto de física que mais cai. Você precisa saber analisar circuitos simples, com resistores em série (a corrente é a mesma) e em paralelo (a tensão é a mesma). Questões sobre o funcionamento de aparelhos domésticos, consumo de energia (em kWh), chuveiros elétricos (relação entre potência, resistência e temperatura) e curto-circuito são muito comuns.', 'Por que ao ligar o chuveiro na posição "inverno" (mais quente) a conta de luz aumenta? Porque na posição inverno a resistência é menor, o que, pela Lei de Ohm, aumenta a corrente e, consequentemente, a potência (P=R.i²).', 'theory', 'hard', 25),

('Física', 'Eletricidade e Magnetismo', 'Eletrostática (cargas, campo elétrico)', 'Este tema é extremamente relevante para o mundo moderno e muito cobrado no ENEM, principalmente a parte de circuitos elétricos.', 'O estudo das cargas elétricas em repouso. Conceitos: carga elétrica, processos de eletrização (atrito, contato, indução), força elétrica (Lei de Coulomb) e campo elétrico.', 'A prova foca nos conceitos. Você precisa entender como os corpos se eletrizam e o que acontece com as cargas. O conceito de campo elétrico como uma região de influência de uma carga é importante, mas os cálculos da Lei de Coulomb são menos frequentes que os de circuitos.', 'Uma questão pode descrever um experimento onde um bastão de vidro atrai pedaços de papel e perguntar qual o processo de eletrização envolvido (indução).', 'theory', 'medium', 20),

('Física', 'Eletricidade e Magnetismo', 'Magnetismo (campo magnético, força magnética)', 'Este tema é extremamente relevante para o mundo moderno e muito cobrado no ENEM, principalmente a parte de circuitos elétricos.', 'O estudo dos fenômenos relacionados a ímãs e campos magnéticos. Conceitos: polos magnéticos, campo magnético (gerado por ímãs ou por correntes elétricas - Experiência de Oersted), força magnética e indução eletromagnética.', 'O foco é conceitual. Entender que não existem monopolos magnéticos, como funcionam bússolas e o campo magnético da Terra. A relação entre eletricidade e magnetismo é crucial: corrente elétrica gera campo magnético (base dos eletroímãs) e a variação do campo magnético gera corrente elétrica (base dos geradores e usinas de energia).', 'Entender o princípio de funcionamento de um motor elétrico (força magnética atuando em um fio com corrente) ou de uma usina hidrelétrica (a água move uma turbina, que gira um ímã perto de uma bobina, induzindo uma corrente elétrica).', 'theory', 'medium', 22),

-- Termologia e Ondulatória
('Física', 'Termologia e Ondulatória', 'Calorimetria (calor sensível e latente, trocas de calor)', 'Fenômenos relacionados ao calor, temperatura, som e luz. São temas muito visuais e presentes no nosso dia a dia.', 'O estudo das trocas de calor. Temperatura é a medida da agitação das partículas. Calor é a energia térmica em trânsito. Calor Sensível é o que causa variação de temperatura (Q=mcΔT). Calor Latente é o que causa mudança de estado físico (Q=mL).', 'O ENEM cobra o entendimento desses conceitos em situações práticas, como o porquê de sentirmos frio ao sair molhados da piscina (a água evapora, "roubando" calor do nosso corpo) ou por que a panela de pressão cozinha mais rápido (a pressão aumenta o ponto de ebulição da água). Cálculos de trocas de calor em sistemas isolados (a soma dos calores trocados é zero) também são comuns.', 'Calcular a quantidade de calor necessária para transformar um bloco de gelo a -10°C em água a 20°C, envolvendo calor sensível do gelo, calor latente de fusão e calor sensível da água.', 'theory', 'medium', 20),

('Física', 'Termologia e Ondulatória', 'Termodinâmica', 'Fenômenos relacionados ao calor, temperatura, som e luz. São temas muito visuais e presentes no nosso dia a dia.', 'O estudo das relações entre calor, trabalho e energia, principalmente em gases. É a base do funcionamento de motores e refrigeradores.', 'A 1ª Lei da Termodinâmica (conservação de energia: ΔU = Q - W) é a mais importante. As questões geralmente envolvem a análise de transformações gasosas (isobárica, isocórica, isotérmica) e o funcionamento de máquinas térmicas, pedindo para identificar o rendimento ou analisar o ciclo em um gráfico PxV.', 'Uma questão pode descrever o ciclo de um motor de carro e perguntar em qual etapa o gás realiza trabalho ou recebe calor, analisando um gráfico.', 'theory', 'hard', 25),

('Física', 'Termologia e Ondulatória', 'Ondulatória (fenômenos como refração, reflexão, difração)', 'Fenômenos relacionados ao calor, temperatura, som e luz. São temas muito visuais e presentes no nosso dia a dia.', 'O estudo das ondas (mecânicas, como o som, ou eletromagnéticas, como a luz). Conceitos: frequência, período, comprimento de onda, amplitude e velocidade (v=λf).', 'O mais importante é entender os fenômenos ondulatórios: Reflexão (a onda bate e volta), Refração (a onda muda de meio e de velocidade), Difração (a onda contorna obstáculos), Interferência (ondas se somam ou se anulam) e Polarização. O ENEM cobra a identificação desses fenômenos em situações cotidianas.', 'Entender que o eco é um exemplo de reflexão do som, que um fone de ouvido com cancelamento de ruído usa interferência destrutiva, e que a luz passando por uma fresta e se espalhando é um exemplo de difração.', 'theory', 'medium', 18),

('Física', 'Termologia e Ondulatória', 'Óptica (lentes, espelhos, problemas de visão)', 'Fenômenos relacionados ao calor, temperatura, som e luz. São temas muito visuais e presentes no nosso dia a dia.', 'O ramo da física que estuda a luz e os fenômenos da visão.', 'A formação de imagens em espelhos planos e esféricos e em lentes delgadas (convergentes e divergentes) é o ponto central. O ENEM adora questões sobre o olho humano e seus defeitos de visão: Miopia (dificuldade de ver de longe, corrigida com lente divergente) e Hipermetropia (dificuldade de ver de perto, corrigida com lente convergente).', 'Uma questão pode mostrar o esquema de um olho míope, onde a imagem se forma antes da retina, e perguntar qual tipo de lente deve ser usada para corrigir o problema.', 'theory', 'medium', 20);