-- Continuação - Inserir conteúdo de Química
INSERT INTO public.subject_contents (subject, grande_tema, title, description, detailed_explanation, explanation, examples, content_type, difficulty_level, estimated_time) VALUES

-- Química Geral e Físico-Química
('Química', 'Química Geral e Físico-Química', 'Estrutura Atômica e Tabela Periódica', 'É a base que explica como a matéria é formada e como ela se transforma.', 'O estudo do átomo (prótons, nêutrons, elétrons) e a organização dos elementos na Tabela Periódica.', 'Entender a distribuição eletrônica é fundamental para prever o comportamento de um elemento. Da Tabela Periódica, o mais importante é compreender as propriedades periódicas (raio atômico, energia de ionização, eletronegatividade) e como elas variam, pois isso explica por que e como os átomos se ligam.', 'Comparar o raio atômico de dois elementos com base em sua posição na tabela para prever qual deles formará um cátion mais facilmente.', 'theory', 'medium', 20),

('Química', 'Química Geral e Físico-Química', 'Ligações Químicas e Forças Intermoleculares', 'É a base que explica como a matéria é formada e como ela se transforma.', 'Ligações Químicas unem os átomos para formar moléculas (Iônica, Covalente, Metálica). Forças Intermoleculares unem as moléculas umas às outras (Dipolo-dipolo, Ligação de Hidrogênio, Forças de London).', 'Este tópico é crucial para entender as propriedades das substâncias. A polaridade de uma ligação e de uma molécula determina o tipo de força intermolecular, que por sua vez explica propriedades como ponto de ebulição, solubilidade ("semelhante dissolve semelhante") e estado físico.', 'Explicar por que o álcool (etanol) se dissolve na água (ambos são polares e fazem ligações de hidrogênio), mas o óleo não (é apolar).', 'theory', 'medium', 25),

('Química', 'Química Geral e Físico-Química', 'Soluções e Cálculo de Concentração', 'É a base que explica como a matéria é formada e como ela se transforma.', 'O estudo de misturas homogêneas (soluções), formadas por um soluto (o que é dissolvido) e um solvente (o que dissolve).', 'O cálculo das diferentes formas de concentração é muito cobrado: concentração comum (g/L), molaridade (mol/L), título (% em massa ou volume) e ppm (partes por milhão). As questões geralmente envolvem a preparação ou a diluição de soluções em contextos como medicina, indústria de alimentos ou controle de poluição.', 'Calcular a massa de sal necessária para preparar 500 mL de soro fisiológico com concentração de 9 g/L.', 'theory', 'hard', 22),

('Química', 'Química Geral e Físico-Química', 'Termoquímica (entalpia, reações exo/endotérmicas)', 'É a base que explica como a matéria é formada e como ela se transforma.', 'O estudo do calor envolvido nas reações químicas. Entalpia (H) é o conteúdo de energia de uma substância. Reações exotérmicas liberam calor (ΔH < 0), enquanto reações endotérmicas absorvem calor (ΔH > 0).', 'O ENEM cobra a identificação de processos exo/endotérmicos no cotidiano (combustão é exotérmica, fotossíntese é endotérmica). A Lei de Hess (o ΔH total não depende do caminho da reação) pode aparecer em questões que pedem para calcular a variação de entalpia de uma reação a partir de outras.', 'Analisar um gráfico de entalpia de uma reação para determinar se ela é exotérmica ou endotérmica e calcular o valor do ΔH.', 'theory', 'medium', 20),

('Química', 'Química Geral e Físico-Química', 'Cinética e Equilíbrio Químico', 'É a base que explica como a matéria é formada e como ela se transforma.', 'Cinética estuda a velocidade das reações e os fatores que a influenciam (temperatura, concentração, superfície de contato, catalisadores). Equilíbrio é o estado em que a velocidade da reação direta se iguala à da inversa.', 'Para cinética, o foco é qualitativo: entender por que alimentos cozinham mais rápido na panela de pressão (maior temperatura e pressão) ou por que um comprimido efervescente se dissolve mais rápido em pó (maior superfície de contato). Para equilíbrio, o Princípio de Le Chatelier é a estrela: "Quando um sistema em equilíbrio é perturbado, ele se desloca no sentido de anular essa perturbação".', 'Em uma reação em equilíbrio, prever para que lado a reação se desloca se aumentarmos a pressão, a temperatura ou a concentração de um dos reagentes.', 'theory', 'hard', 25),

-- Química Orgânica
('Química', 'Química Orgânica', 'Funções Orgânicas (álcool, cetona, ácidos, etc.)', 'O estudo dos compostos de carbono. É uma parte enorme da química, mas o ENEM foca nos conceitos mais aplicados.', 'É a classificação dos compostos orgânicos com base em seus grupos funcionais.', 'O mais importante é reconhecer as principais funções: hidrocarbonetos, álcool, fenol, éter, aldeído, cetona, ácido carboxílico, éster, amina e amida. Saber a nomenclatura básica ajuda, mas o reconhecimento da estrutura e a associação com suas propriedades (ex: ácidos carboxílicos são ácidos, aminas são básicas) é o principal.', 'Dada a fórmula estrutural do paracetamol, identificar as funções fenol e amida presentes na molécula.', 'theory', 'medium', 22),

('Química', 'Química Orgânica', 'Reações Orgânicas Principais', 'O estudo dos compostos de carbono. É uma parte enorme da química, mas o ENEM foca nos conceitos mais aplicados.', 'Os processos de transformação que os compostos orgânicos sofrem.', 'O ENEM não espera que você decore mecanismos complexos. O foco é em reações de grande importância industrial ou biológica: Combustão (de combustíveis fósseis), Esterificação (formação de essências e gorduras), Saponificação (produção de sabão), Oxidação (de álcoois, como no teste do bafômetro) e Polimerização.', 'Entender que a reação entre um ácido carboxílico (vinagre) e um álcool (álcool de cozinha) forma um éster, que tem cheiro de fruta.', 'theory', 'medium', 20),

('Química', 'Química Orgânica', 'Isomeria (plana e espacial)', 'O estudo dos compostos de carbono. É uma parte enorme da química, mas o ENEM foca nos conceitos mais aplicados.', 'O fenômeno em que duas ou mais substâncias diferentes possuem a mesma fórmula molecular. Isomeria Plana (de função, de cadeia, de posição). Isomeria Espacial ou Estereoisomeria (Geométrica cis-trans e Óptica).', 'A isomeria explica por que compostos com a mesma "receita" (fórmula molecular) podem ter cheiros, sabores e efeitos biológicos completamente diferentes. A isomeria geométrica (cis-trans) é importante em gorduras e visão. A isomeria óptica (quiralidade) é fundamental em fármacos e bioquímica.', 'Entender a diferença entre a gordura cis (saudável) e a gordura trans (prejudicial), que são isômeros geométricos.', 'theory', 'hard', 25),

('Química', 'Química Orgânica', 'Polímeros', 'O estudo dos compostos de carbono. É uma parte enorme da química, mas o ENEM foca nos conceitos mais aplicados.', 'Macromoléculas formadas pela repetição de pequenas unidades (monômeros).', 'O ENEM aborda os polímeros de grande importância comercial e cotidiana: plásticos (PET, PVC, PE), borrachas, nylon, e também polímeros naturais como carboidratos (amido, celulose) e proteínas. É importante saber reconhecer a unidade de repetição (o monômero) e o tipo de reação que forma o polímero (adição ou condensação).', 'Uma questão pode mostrar a estrutura do polímero PET e pedir para identificar o monômero ou a função orgânica (éster) que se repete.', 'theory', 'medium', 18),

-- Química Ambiental e Inorgânica
('Química', 'Química Ambiental e Inorgânica', 'Poluição (água, solo, ar)', 'A aplicação da química para entender o mundo ao nosso redor, desde a poluição até os produtos de limpeza.', 'A introdução de substâncias ou energia no ambiente, causando impacto negativo.', 'Este é um tema interdisciplinar (dialoga com Biologia e Geografia). Conceitos importantes: Efeito Estufa (gases como CO₂ e CH₄), Chuva Ácida (óxidos de enxofre e nitrogênio), Destruição da Camada de Ozônio (CFCs) e Eutrofização (excesso de nutrientes na água).', 'Uma questão pode relacionar o aumento da queima de combustíveis fósseis com a intensificação do efeito estufa ou com a formação de chuva ácida.', 'theory', 'medium', 20),

('Química', 'Química Ambiental e Inorgânica', 'Lixo e Reciclagem', 'A aplicação da química para entender o mundo ao nosso redor, desde a poluição até os produtos de limpeza.', 'O estudo do destino dos resíduos sólidos e dos processos para reaproveitá-los.', 'Entender os diferentes tipos de materiais (metais, vidros, plásticos, papel) e os processos básicos de sua reciclagem. A coleta seletiva e a simbologia da reciclagem são temas recorrentes.', 'Uma questão pode apresentar os símbolos de reciclagem de diferentes plásticos e pedir para associá-los a seus usos comuns (ex: PET em garrafas).', 'theory', 'easy', 15),

('Química', 'Química Ambiental e Inorgânica', 'Funções Inorgânicas (ácidos, bases, sais e óxidos)', 'A aplicação da química para entender o mundo ao nosso redor, desde a poluição até os produtos de limpeza.', 'A classificação dos compostos que não são orgânicos.', 'O foco é no comportamento e nas aplicações. Ácidos e Bases (conceito de Arrhenius, escala de pH, reações de neutralização). Sais (formados na neutralização). Óxidos (e sua classificação em ácidos, básicos, neutros ou anfóteros). As questões contextualizam esses compostos em produtos de limpeza, alimentos, chuva ácida, etc.', 'Entender por que se joga cal (um óxido básico) em solos ácidos para corrigir o pH, através de uma reação de neutralização.', 'theory', 'medium', 22),

('Química', 'Química Ambiental e Inorgânica', 'Estequiometria', 'A aplicação da química para entender o mundo ao nosso redor, desde a poluição até os produtos de limpeza.', 'O cálculo das quantidades de reagentes e produtos envolvidos em uma reação química, com base nas leis de conservação de massa.', 'É a "matemática da química". Aparece em muitas questões, de forma direta ou indireta. Você precisa saber balancear uma equação química e usar a proporção em mols (dada pelos coeficientes) para calcular massas, volumes ou número de partículas. Casos de reagente limitante/excesso e pureza/rendimento são comuns.', 'Na queima completa de 160g de metano (CH₄), qual a massa de dióxido de carbono (CO₂) produzida? Você precisa montar e balancear a equação, converter a massa de metano para mols, usar a proporção da equação para achar os mols de CO₂ e, por fim, converter de volta para massa.', 'theory', 'hard', 30);