-- Finalização - Inserir conteúdo de História
INSERT INTO public.subject_contents (subject, grande_tema, title, description, detailed_explanation, explanation, examples, content_type, difficulty_level, estimated_time) VALUES

-- História do Brasil
('História', 'História do Brasil', 'Brasil Colônia (economia açucareira, mineração)', 'É a parte mais cobrada de História, com foco nos processos sociais, políticos e econômicos que formaram o país.', 'O período em que o Brasil foi colônia de Portugal (1500-1822).', 'Entender a lógica do Pacto Colonial e da economia baseada no plantation (latifúndio, monocultura, mão de obra escrava, produção para exportação). A sociedade era patriarcal e escravista. A mineração no século XVIII deslocou o eixo econômico para o Sudeste e aumentou o controle de Portugal. As revoltas coloniais (ex: Inconfidência Mineira) mostram os primeiros anseios por autonomia.', 'Analisar um texto sobre a vida em um engenho de açúcar, identificando as relações de poder entre senhores, escravos e trabalhadores livres.', 'theory', 'medium', 25),

('História', 'História do Brasil', 'Brasil Império (Primeiro e Segundo Reinado, Crise da Monarquia)', 'É a parte mais cobrada de História, com foco nos processos sociais, políticos e econômicos que formaram o país.', 'O período monárquico do Brasil (1822-1889).', 'O Primeiro Reinado foi marcado pelo autoritarismo de D. Pedro I. O Período Regencial foi uma época de instabilidade e revoltas. O Segundo Reinado (D. Pedro II) foi um longo período de estabilidade política (baseada no "parlamentarismo às avessas") e transformações econômicas (auge do café). O processo de abolição da escravatura e a Guerra do Paraguai são temas centrais que levaram à crise e queda da monarquia.', 'Uma questão pode usar uma charge da época para criticar o Poder Moderador ou discutir o papel dos imigrantes europeus que vieram substituir a mão de obra escrava nas lavouras de café.', 'theory', 'medium', 25),

('História', 'História do Brasil', 'República Velha e Era Vargas', 'É a parte mais cobrada de História, com foco nos processos sociais, políticos e econômicos que formaram o país.', 'A República Velha (1889-1930) foi marcada pelo domínio das oligarquias (política do "café com leite") e pelo coronelismo. A Era Vargas (1930-1945) foi um período de centralização do poder, industrialização, criação das leis trabalhistas (CLT) e forte propaganda política, passando por fases como o Estado Novo (ditadura).', 'Entender as estruturas de poder da República Velha (voto de cabresto, clientelismo). Sobre Vargas, é crucial compreender seu caráter populista, a modernização econômica e a manipulação das massas através do rádio e da propaganda oficial (DIP).', 'Analisar um cartaz de propaganda do Estado Novo e identificar os elementos que buscam exaltar a figura de Getúlio Vargas como "pai dos pobres".', 'theory', 'medium', 25),

('História', 'História do Brasil', 'Ditadura Militar e Redemocratização', 'É a parte mais cobrada de História, com foco nos processos sociais, políticos e econômicos que formaram o país.', 'A Ditadura Militar (1964-1985) foi um regime autoritário que suprimiu direitos políticos e perseguiu opositores, enquanto a Redemocratização (pós-1985) marcou o retorno ao regime democrático no Brasil.', 'Compreender os Atos Institucionais (AI-5), o "milagre econômico" e a repressão política. Na redemocratização, focar nas Diretas Já, na Constituição de 1988 e nos desafios da Nova República.', 'Discutir como a música "Pra Não Dizer que Não Falei das Flores" (Caminhando) de Geraldo Vandré se tornou um hino de resistência à Ditadura Militar, refletindo o contexto de censura e repressão da época.', 'theory', 'hard', 30),

-- História Geral
('História', 'História Geral', 'Antiguidade e Idade Média', 'Aborda os grandes processos históricos globais, com um olhar para as conexões e impactos no presente.', 'A Antiguidade abrange civilizações como Egito, Grécia e Roma. A Idade Média se estende da queda do Império Romano (476 d.C.) até a queda de Constantinopla (1453), caracterizada pelo feudalismo na Europa e o avanço do Islamismo.', 'Foco na herança cultural greco-romana (democracia, direito) e nas estruturas sociais do feudalismo (clero, nobreza, servos). O papel da Igreja e as Cruzadas também são importantes.', 'Comparar as noções de cidadania na Grécia Antiga com as da Roma Antiga, ou analisar as relações de suserania e vassalagem no contexto feudal.', 'theory', 'medium', 22),

('História', 'História Geral', 'Idade Moderna (Renascimento, Reformas, Absolutismo)', 'Aborda os grandes processos históricos globais, com um olhar para as conexões e impactos no presente.', 'Período de transição para a contemporaneidade (séculos XV-XVIII), marcado pelo Renascimento (humanismo e novas artes), Reforma Protestante (quebra da unidade religiosa), Grandes Navegações (expansão marítima e colonialismo) e o Absolutismo (monarquias centralizadas).', 'Entender o antropocentrismo do Renascimento, as críticas à Igreja que levaram às Reformas (Lutero, Calvino) e a formação dos Estados Nacionais e o mercantilismo como política econômica colonialista.', 'Analisar uma obra de arte renascentista, como a "Mona Lisa", e discutir seus elementos humanistas e o uso da perspectiva. Ou entender o papel do Rei Sol, Luís XIV, como símbolo do absolutismo.', 'theory', 'medium', 25),

('História', 'História Geral', 'Iluminismo e Revoluções Liberais', 'Aborda os grandes processos históricos globais, com um olhar para as conexões e impactos no presente.', 'O Iluminismo (século XVIII) foi um movimento intelectual que valorizava a razão e a crítica ao Antigo Regime. Suas ideias inspiraram a Revolução Francesa (1789) e a Revolução Industrial (início na Inglaterra, século XVIII), transformando política, sociedade e economia.', 'As ideias iluministas (liberdade, igualdade, divisão de poderes) e seu impacto na crise do absolutismo. As consequências da Revolução Francesa (declaração de direitos, fim dos privilégios) e as transformações sociais (surgimento da classe operária, urbanização) e tecnológicas da Revolução Industrial.', 'Relacionar a teoria da separação dos poderes de Montesquieu com a estrutura de governos democráticos atuais, ou discutir o impacto da máquina a vapor na produção têxtil e na vida dos trabalhadores.', 'theory', 'medium', 25),

('História', 'História Geral', 'Século XX (Guerras Mundiais, Guerra Fria, Globalização)', 'Aborda os grandes processos históricos globais, com um olhar para as conexões e impactos no presente.', 'Um século de grandes conflitos e transformações. Inclui a Primeira (1914-1918) e Segunda (1939-1945) Guerras Mundiais, a Guerra Fria (conflito ideológico EUA x URSS, 1947-1991) e o processo de Globalização (intensificação das interconexões mundiais).', 'As causas e consequências das Guerras Mundiais (Tratado de Versalhes, ascensão de regimes totalitários, Holocausto, criação da ONU). A bipolaridade da Guerra Fria (Muro de Berlim, Corrida Armamentista e Espacial) e a emergência da Globalização (avanços tecnológicos, neoliberalismo, blocos econômicos).', 'Explicar como a Crise de 1929 e a ascensão do Nazismo na Alemanha foram fatores que contribuíram para a eclosão da Segunda Guerra Mundial, ou analisar um mapa das divisões ideológicas durante a Guerra Fria.', 'theory', 'hard', 30);