
-- Atualizar os tópicos existentes com explicações detalhadas para estudo

-- Inglês - Interpretação de Gêneros Textuais
UPDATE subject_contents 
SET detailed_explanation = 'A interpretação de textos jornalísticos e publicitários no ENEM exige técnicas específicas. Use Skimming para captar a ideia geral rapidamente - leia o título, subtítulos e primeiro parágrafo. Use Scanning para encontrar informações específicas - procure palavras-chave relacionadas à pergunta. Textos jornalísticos seguem a estrutura: lead (quem, o que, quando, onde, por que), desenvolvimento e conclusão. Textos publicitários usam linguagem persuasiva, imperativo e apelo emocional. Observe sempre o público-alvo e a finalidade do texto.',
examples = 'Exemplo 1: Ao ler uma notícia da BBC sobre mudanças climáticas, identifique primeiro o fato principal no lead, depois procure dados específicos como percentuais ou datas mencionadas na pergunta. Exemplo 2: Em um anúncio publicitário, identifique as estratégias persuasivas: uso de celebridades, promessas de benefícios, criação de urgência ("oferta limitada"), e como isso se relaciona com o público-alvo.',
practical_applications = 'No ENEM, você encontrará textos de sites como BBC, CNN, The Guardian. A chave é não se desesperar com palavras desconhecidas - foque no contexto. Use cognatos (palavras parecidas com o português) a seu favor. Pratique com textos curtos primeiro, depois aumente a complexidade. Sempre leia a pergunta antes do texto para saber o que procurar.',
study_tips = 'Dica 1: Leia notícias em inglês 10 minutos por dia. Dica 2: Pratique técnicas de scanning com textos que você já conhece em português. Dica 3: Faça um vocabulário de palavras-chave comuns em cada tipo de texto. Dica 4: Pratique identificar a ideia principal em 30 segundos.'
WHERE subject = 'Inglês' AND title = 'Análise de textos jornalísticos e publicitários';

UPDATE subject_contents 
SET detailed_explanation = 'Tirinhas, charges e poemas exigem compreensão da linguagem verbal e não-verbal. Na interpretação, analise a relação entre imagem e texto - muitas vezes a piada ou mensagem está nessa interação. Em tirinhas, observe a sequência temporal e as expressões dos personagens. Em charges, identifique a crítica social ou política implícita. Em poemas, foque no sentido figurado e no tema central, não se prenda a entender cada palavra isoladamente.',
examples = 'Exemplo 1: Uma tirinha do Garfield onde ele odeia segundas-feiras - o humor está na personificação e exagero. Exemplo 2: Uma charge sobre política onde um político aparece como um animal - identifique que animal e por que (leão = força, rato = covardia). Exemplo 3: Um poema sobre amor onde se compara o sentimento com uma tempestade - foque na metáfora, não nas palavras isoladas.',
practical_applications = 'No ENEM, charges e tirinhas aparecem frequentemente. Observe sempre: 1) O contexto histórico ou social, 2) A ironia ou humor, 3) A crítica implícita, 4) Os elementos visuais que complementam o texto. Para poemas, identifique o eu-lírico, o sentimento predominante e a mensagem principal.',
study_tips = 'Dica 1: Pratique com tirinhas famosas (Calvin e Hobbes, Peanuts). Dica 2: Analise charges de jornais brasileiros em inglês. Dica 3: Para poemas, leia em voz alta para captar o ritmo. Dica 4: Sempre conecte o texto com seu conhecimento de mundo.'
WHERE subject = 'Inglês' AND title = 'Interpretação de tirinhas, charges e poemas';

UPDATE subject_contents 
SET detailed_explanation = 'Letras de música e textos literários exploram temas subjetivos e emocionais. O objetivo é captar o tema central, o sentimento do eu-lírico/narrador e a mensagem principal. Em músicas, observe a repetição de palavras-chave, o tom (alegre, melancólico, protesto) e o contexto social. Em textos literários, identifique o narrador, o conflito principal e o desfecho. Não se prenda a detalhes menores - foque na essência da mensagem.',
examples = 'Exemplo 1: "Imagine" de John Lennon - tema central é paz mundial, o eu-lírico convida a imaginar um mundo sem divisões. Exemplo 2: Trecho de "To Kill a Mockingbird" - foque no tema do preconceito racial e na perspectiva da narradora criança. Exemplo 3: Música de protesto dos anos 60 - identifique a crítica social e o chamado à ação.',
practical_applications = 'No ENEM, aparcem trechos de autores como Shakespeare, Mark Twain, ou letras de músicas famosas. Identifique sempre: 1) O tema principal, 2) O tom emocional, 3) A mensagem ou crítica social, 4) O público-alvo. Use seu conhecimento cultural para entender referências históricas ou sociais.',
study_tips = 'Dica 1: Ouça músicas em inglês e leia as letras simultaneamente. Dica 2: Comece com textos de autores que você já conhece em português. Dica 3: Foque mais no "que" está sendo dito do que no "como". Dica 4: Conecte o texto com eventos históricos ou movimentos sociais.'
WHERE subject = 'Inglês' AND title = 'Compreensão de letras de música e textos literários';

-- Inglês - Vocabulário e Estruturas da Língua
UPDATE subject_contents 
SET detailed_explanation = 'O vocabulário contextual é fundamental no ENEM. Você não precisa saber todas as palavras, mas deve inferir significados pelo contexto. Cognatos são seus aliados - palavras como "university", "hospital", "natural" são similares ao português. Observe prefixos e sufixos: "un-" = negação, "-tion" = substantivo, "-ly" = advérbio. Use as palavras ao redor para deduzir significados. Expressões idiomáticas têm sentido figurado - "break a leg" não significa quebrar a perna, mas "boa sorte".',
examples = 'Exemplo 1: "The library was enormous" - mesmo sem saber "enormous", o contexto de biblioteca + "was" indica uma característica, provavelmente "grande". Exemplo 2: "She felt blue after the breakup" - "blue" aqui não é cor, mas tristeza. Exemplo 3: Cognatos: "information/informação", "transportation/transporte", "education/educação".',
practical_applications = 'No ENEM, foque em: 1) Palavras-chave que respondem à pergunta, 2) Cognatos que facilitam compreensão, 3) Conectivos que mostram relações entre ideias, 4) Prefixos/sufixos que indicam função gramatical. Não pare na primeira palavra desconhecida - continue lendo para captar o sentido geral.',
study_tips = 'Dica 1: Mantenha uma lista de cognatos comuns. Dica 2: Pratique inferir significados sem usar dicionário. Dica 3: Estude prefixos e sufixos mais comuns. Dica 4: Leia textos variados para ampliar vocabulário passivo.'
WHERE subject = 'Inglês' AND title = 'Vocabulário em contexto e expressões idiomáticas';

UPDATE subject_contents 
SET detailed_explanation = 'Falsos cognatos são "pegadinhas" frequentes no ENEM - palavras que parecem com português mas têm significados diferentes. Phrasal verbs são verbos + preposição com significado específico. Memorize os falsos cognatos mais comuns: "actually" = na verdade (não "atualmente"), "library" = biblioteca (não "livraria"), "pretend" = fingir (não "pretender"), "realize" = perceber (não "realizar"). Phrasal verbs mudam completamente o sentido: "give up" = desistir, "look after" = cuidar.',
examples = 'Falsos cognatos: "I actually finished my homework" = Na verdade terminei minha lição. "She pretends to be sick" = Ela finge estar doente. "The library is closed" = A biblioteca está fechada. Phrasal verbs: "Turn off the lights" = Apague as luzes. "I ran into my teacher" = Encontrei meu professor por acaso.',
practical_applications = 'No ENEM, falsos cognatos aparecem em opções de múltipla escolha para confundir. Leia com atenção e confirme o significado pelo contexto. Para phrasal verbs, foque nos mais comuns: turn on/off, give up, look for, take care of. Muitas vezes o significado é diferente do verbo isolado.',
study_tips = 'Dica 1: Crie flashcards com falsos cognatos mais comuns. Dica 2: Pratique phrasal verbs em contexto, não isoladamente. Dica 3: Quando suspeitar de falso cognato, releia a frase inteira. Dica 4: Estude listas de falsos cognatos específicas para ENEM.'
WHERE subject = 'Inglês' AND title = 'Reconhecimento de "phrasal verbs" e falsos cognatos';

UPDATE subject_contents 
SET detailed_explanation = 'Tempos verbais e conectores são essenciais para compreensão textual. Conectores (linking words) mostram relações entre ideias: "however/but" = oposição, "therefore/so" = conclusão, "although/despite" = concessão, "because/since" = causa. Tempos verbais indicam quando ações acontecem: Simple Past para ações concluídas, Present Perfect para ações que afetam o presente, Future para planos/previsões. Esses elementos são cruciais para entender a cronologia e lógica do texto.',
examples = 'Conectores: "I studied hard, however I failed" = estudei muito, porém reprovei. "It was raining, therefore we stayed home" = estava chovendo, portanto ficamos em casa. Tempos: "I worked yesterday" (passado simples). "I have worked here for 5 years" (presente perfeito - ainda trabalho). "I will work tomorrow" (futuro).',
practical_applications = 'No ENEM, conectores ajudam a entender a estrutura argumentativa do texto. Identifique se o autor está: concordando, discordando, exemplificando, concluindo. Tempos verbais ajudam na cronologia dos eventos e na compreensão de causa e efeito.',
study_tips = 'Dica 1: Faça uma tabela com conectores e seus significados. Dica 2: Pratique identificar a função de cada conector em textos. Dica 3: Para tempos verbais, foque nos mais comuns: Simple Past, Present Perfect, Future. Dica 4: Observe como conectores estruturam parágrafos.'
WHERE subject = 'Inglês' AND title = 'Tempos verbais e Conectores (linking words)';

-- Inglês - Atualidades e Análise Crítica
UPDATE subject_contents 
SET detailed_explanation = 'Textos sobre temas sociais, tecnologia e meio ambiente são muito comuns no ENEM. Estes temas refletem preocupações globais atuais: diversidade e inclusão, impacto das redes sociais, sustentabilidade, mudanças climáticas, inteligência artificial. Para interpretar bem, conecte o texto com seu conhecimento sobre esses temas em português. O vocabulário específico se repete: "environment/meio ambiente", "sustainable/sustentável", "diversity/diversidade", "technology/tecnologia", "social media/redes sociais".',
examples = 'Exemplo 1: Texto sobre aquecimento global - vocabulário chave: "greenhouse effect", "carbon emissions", "renewable energy". Exemplo 2: Texto sobre redes sociais - termos como "cyberbullying", "privacy", "digital divide". Exemplo 3: Texto sobre diversidade - "inclusion", "equality", "discrimination", "minorities".',
practical_applications = 'No ENEM, esses temas aparecem em textos argumentativos onde você deve identificar: 1) O problema apresentado, 2) As causas, 3) As consequências, 4) As soluções propostas. Use seu conhecimento prévio sobre esses assuntos para facilitar a compreensão.',
study_tips = 'Dica 1: Acompanhe notícias sobre esses temas em sites em inglês. Dica 2: Crie um glossário com vocabulário específico de cada tema. Dica 3: Conecte sempre com o que você já sabe sobre o assunto. Dica 4: Pratique com textos de organizações como UN, UNESCO, WHO.'
WHERE subject = 'Inglês' AND title = 'Leitura de temas sociais, tecnologia e meio ambiente';

-- Espanhol - Interpretação e Análise Textual
UPDATE subject_contents 
SET detailed_explanation = 'A interpretação de textos em espanhol segue princípios similares ao inglês, mas com maior proximidade ao português. Em notícias e artigos de jornais como El País, identifique a estrutura: titular, subtítulo, lead e desenvolvimento. Artigos de opinião apresentam tese, argumentos e conclusão. A estratégia é a mesma: Skimming para ideia geral, Scanning para informações específicas. Observe marcadores textuais como "sin embargo" (no entanto), "por tanto" (portanto), "además" (além disso) que organizam as ideias.',
examples = 'Exemplo 1: Notícia sobre economia - identifique dados específicos como percentuais "el 15% de la población" e datas "en enero de 2024". Exemplo 2: Artigo de opinião sobre educação - identifique a posição do autor no primeiro parágrafo e os argumentos que a sustentam. Exemplo 3: Publicidade de produto - observe o imperativo "compre", "visite", "descubra" e os benefícios prometidos.',
practical_applications = 'No ENEM, textos em espanhol abordam temas latino-americanos e espanhóis. Contextualize com seu conhecimento sobre esses países. Observe diferenças culturais nas notícias. Use a proximidade com o português a seu favor, mas cuidado com falsos cognatos.',
study_tips = 'Dica 1: Leia notícias do El País, La Nación ou Clarín diariamente. Dica 2: Compare a mesma notícia em português e espanhol. Dica 3: Pratique identificar a opinião do autor em editoriais. Dica 4: Observe como cada país hispânico usa expressões diferentes.'
WHERE subject = 'Espanhol' AND title = 'Leitura de notícias, artigos de opinião e publicidade';

UPDATE subject_contents 
SET detailed_explanation = 'Mafalda, criada por Quino, é uma personagem icônica que aparece frequentemente no ENEM. Suas tirinhas abordam temas como política, sociedade, família e filosofia com humor inteligente. Para interpretar, observe: 1) O contexto histórico (Guerra Fria, ditaduras latino-americanas), 2) A crítica social implícita, 3) A ironia na fala das crianças, 4) A relação entre texto e imagem. Mafalda questiona o mundo adulto com inocência aparente, mas demonstra consciência social aguçada.',
examples = 'Exemplo 1: Mafalda questiona por que os adultos poluem o planeta que deixam para as crianças - crítica ambiental. Exemplo 2: Ela pergunta por que existe fome se há comida suficiente - crítica à desigualdade social. Exemplo 3: Questiona a violência na TV - crítica à mídia. A ironia está na simplicidade das perguntas que expõem contradições complexas.',
practical_applications = 'No ENEM, questões sobre Mafalda testam: 1) Compreensão da crítica social, 2) Identificação da ironia, 3) Relação entre contexto histórico e mensagem, 4) Interpretação da linguagem não-verbal (expressões, gestos). Use seu conhecimento sobre problemas sociais para entender as críticas.',
study_tips = 'Dica 1: Leia várias tirinhas de Mafalda para entender o estilo. Dica 2: Pesquise sobre o contexto histórico da Argentina nos anos 60-70. Dica 3: Observe as expressões faciais dos personagens. Dica 4: Conecte as críticas de Mafalda com problemas atuais.'
WHERE subject = 'Espanhol' AND title = 'Análise de tirinhas (cómics), charges e poemas';

UPDATE subject_contents 
SET detailed_explanation = 'Textos literários em espanhol no ENEM incluem autores como García Márquez, Neruda, Octavio Paz. Letras de música abordam temas como amor, identidade latino-americana, problemas sociais. Para interpretar: 1) Identifique o tema central, 2) Observe o tom emocional, 3) Contextualize historicamente, 4) Identifique recursos literários (metáforas, simbolismos). O realismo mágico é comum na literatura hispano-americana - aceite elementos fantásticos como parte da narrativa.',
examples = 'Exemplo 1: Trecho de "Cem Anos de Solidão" - mistura realidade e fantasia, tema da solidão latino-americana. Exemplo 2: Poema de Neruda sobre amor - linguagem sensorial, metáforas com elementos da natureza. Exemplo 3: Música protesto sobre ditadura - linguagem metafórica para evitar censura, tom melancólico.',
practical_applications = 'No ENEM, foque em: 1) Tema principal da obra, 2) Contexto histórico-social, 3) Sentimentos do eu-lírico/narrador, 4) Recursos expressivos utilizados. Use conhecimento sobre história da América Latina para entender referências políticas e sociais.',
study_tips = 'Dica 1: Leia resumos de obras clássicas hispano-americanas. Dica 2: Ouça música latina prestando atenção nas letras. Dica 3: Estude contexto histórico da América Latina. Dica 4: Pratique identificar figuras de linguagem em espanhol.'
WHERE subject = 'Espanhol' AND title = 'Compreensão de letras de música e fragmentos de romances';

-- Espanhol - Léxico e Estruturas da Língua
UPDATE subject_contents 
SET detailed_explanation = 'Falsos cognatos (heterosemánticos) são a maior armadilha em espanhol. Exemplos críticos: "exquisito" = delicioso (não esquisito), "rato" = momento (não rato), "borracha" = bêbada (não borracha), "salada" = salgada (não salada), "escoba" = vassoura (não escova). Memorize os mais comuns para evitar erros. Diferente do inglês, em espanhol há muitos falsos cognatos por causa da proximidade linguística - isso pode induzir ao erro.',
examples = 'Falsos cognatos em contexto: "La comida está exquisita" = A comida está deliciosa. "Espera un rato" = Espera um momento. "La borracha cantaba" = A bêbada cantava. "La ensalada está salada" = A salada está salgada. "Busco la escoba" = Procuro a vassoura.',
practical_applications = 'No ENEM, falsos cognatos aparecem para confundir em questões de interpretação. Quando uma palavra parecer familiar mas não fizer sentido no contexto, desconfie. Releia a frase toda e use o contexto para confirmar o significado correto.',
study_tips = 'Dica 1: Crie flashcards específicos para falsos cognatos. Dica 2: Pratique frases onde eles aparecem em contexto. Dica 3: Quando em dúvida, use o contexto da frase. Dica 4: Memorize uma lista dos 20 falsos cognatos mais comuns no ENEM.'
WHERE subject = 'Espanhol' AND title = 'Identificação de falsos cognatos (heterosemánticos)';

UPDATE subject_contents 
SET detailed_explanation = 'O vocabulário em espanhol se beneficia da proximidade com o português, mas requer atenção às diferenças. Expressões idiomáticas têm sentido figurado: "estar en las nubes" = estar distraído, "no tener pelos en la lengua" = falar sem rodeios. O vocabulário varia entre países: "auto/coche/carro" para automóvel, "ordenador/computadora" para computador. No ENEM, foque no espanhol "neutro" usado em textos formais.',
examples = 'Vocabulário regional: México: "computadora", Espanha: "ordenador"; Argentina: "auto", Espanha: "coche". Expressões: "Llueve a cántaros" = chove muito, "Dar en el clavo" = acertar em cheio, "Estar como una cabra" = estar louco.',
practical_applications = 'No ENEM, o vocabulário aparece em contextos formais (notícias, artigos) e informais (diálogos, tirinhas). Use cognatos verdadeiros a seu favor: "universidad", "hospital", "natural". Observe prefixos e sufixos similares ao português.',
study_tips = 'Dica 1: Estude vocabulário por temas (família, escola, trabalho). Dica 2: Observe variações regionais mas foque no padrão. Dica 3: Pratique expressões idiomáticas comuns. Dica 4: Use a proximidade com português mas confirme significados.'
WHERE subject = 'Espanhol' AND title = 'Vocabulário e expressões idiomáticas';

UPDATE subject_contents 
SET detailed_explanation = 'A gramática espanhola tem semelhanças com o português mas também diferenças importantes. Tempos verbais: presente, pretérito (passado), futuro funcionam similarmente. Pronomes: "tú/vos" (você), diferenças regionais importantes. Conjunções: "pero" (mas), "aunque" (embora), "porque" (porque). O subjuntivo é mais usado em espanhol que em português. Conectores organizam as ideias: "sin embargo" (porém), "además" (além disso), "por tanto" (portanto).',
examples = 'Tempos verbais: "Yo estudio" (eu estudo), "Yo estudié" (eu estudei), "Yo estudiaré" (eu estudarei). Subjuntivo: "Espero que vengas" (espero que você venha). Conectores: "Estudié mucho, sin embargo no aprobé" (estudei muito, porém não passei).',
practical_applications = 'No ENEM, a gramática aparece contextualizada. Identifique: 1) Tempo da ação pelos verbos, 2) Relações lógicas pelos conectores, 3) Formalidade pelo tratamento usado. Não se prenda a regras gramaticais isoladas - foque na compreensão global.',
study_tips = 'Dica 1: Compare estruturas com o português para identificar semelhanças. Dica 2: Foque nos conectores mais comuns. Dica 3: Observe o uso do subjuntivo em textos. Dica 4: Pratique identificar tempos verbais em contexto.'
WHERE subject = 'Espanhol' AND title = 'Tempos verbais, Pronomes e Conjunções';
