// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mrppwmnyzqgxtjoqpcte.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ycHB3bW55enFneHRqb3FwY3RlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1NjMzMzQsImV4cCI6MjA2NDEzOTMzNH0.U3q3mN2IlqcTwVOWxu-1LobHL-BZtrVKOKW9AKBzBB0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);